
//杏雅三国
export const xinx1Character = {
    xinxying_zhangliao: {
        sex: "male",
        group: "xing",
        hp: 4,
        img: "extension/永夜之境/image/xinxying_zhangliao.png",
        trashBin: ['legend'],
        skills: ['xinxyufu', 'xinxliangye'],
    },
    xxyuexi: ["female", "xing", 3, ["dz_xing_yinxi", "dz_xing_jiangchun"], ['rare']],
    xxin_luxun: ["male", "wu", 3, ['xinxlianyin', 'xinxfenkui'], ["border:xing", 'rare']],
    xinx_zhaoxiang: ["female", "shu", 3, ["xing_xingyu", "xing_ningshuang", 'xing_hanming'], ['legend']],
    xinx_zhangliao: ["male", "xing", 4, ["xxxhuanren", "xxxzhenxi"], ['legend']],
    xinx_lingju: ["female", "qun", 3, ['xinxcangren', 'xinxfenglu'], ['epic']],
    xinx_caoxian: ["female", "wei", 3, ['xing_sizhu', 'xing_mengran'], ['legend']],
    xinx_zhenfu: ["female", "wei", 3, ["xinxsongqu", "xinxfushen", "xinxguizi"], ['epic']],
    xinx_zhaoyun: ["male", "shu", 4, ["xinxchiyu", "xinxshuangmang"], ['rare']],
    xinx_xushao: ["male", "qun", 4, ["xinxshiren", "xinxqianqiu"], ['legend']],
    //xinx_zhouyu: ["male", "wu", 3, ["xinxcangyan", 'xinxzhuoshao'], ["border:xing", 'rare']],
    xinx_jiangwei: ["male", "shu", "2/3", ["xinxpanzhi", "xinxlinyou", "xinxfuhan"], ['epic']],
    xinshu_jiangwei: ["male", "shu", 4, ['xinxbeifa', 'xinxlianbing', 'xinxbugui'], ['rare']],
    xinxqun_jiaxu: ["male", "qun", 3, ['xinxyice', 'xinxwansha'], ['rare']],
    xinwei_zhangliao: ["male", "wei", 4, ['dz_K_huanren', 'dz_K_wuqian'], ['rare']],
    xinx_caoying: ["female", "wei", 4, ['xinxyingfu', 'xinxshixi'], ['epic']],
    xinx_simashi: ["male", "wei", 4, ['xinxqianlong', 'xinxyini', 'xinxchenlan'], ["border:qun", 'legend']],
    xinx_diaochan: ["female", "qun", 3, ['xinxyiyue', 'xinxjuewu'], ['epic']],//'xinxqingchen',
    xinx_caocao: ["male", "wei", 4, ['xinxxieling', 'xinxjianxiong'], ['epic']],
    xinx_guojia: ["male", "wei", 3, ['xinxtianzhi', 'xinxshisheng'], ['epic']],
    xinx_zhonghui: ["male", "wei", 3, ['xinxquanmou', 'xinxwugui'], ["border:qun", 'epic']],
    xinx_jiaxu: ["male", "qun", 3, ['xinxhuoji', 'xinxcanjing', 'xinxsanku'], ['epic']],
    xinx_liutan: ["female", "shu", 3, ['xinxduanzhi', 'xinxjinshu'], ['epic']],
    xinx_huangwudie: ["female", "shu", 4, ['xinxluexin', 'xinxyangjian'], ['epic']],
    xinx_guanyu: ["male", "shu", 4, ['xinxjinbi', 'xinxwusheng'], ['legend']],
    xinx_zhugeliang: ["male", "shu", 2, ['xinxqizhen', 'xinxshiyu', 'xinxlihuo'], ['legend']],
    xinxshu_zhugeliang: ["male", "shu", "4/7", ['xinxxzhaohan', 'xinxrenshi', 'xinxchushi'], ['legend']],
    xinxyin_simashi: ["male", "wei", 3, ['xinxyinshi', 'xinxruilue', 'xinxbainei'], ["border:jin", 'epic']],
    xinx_simayi: ["male", "wei", 3, ['xinxqianyi', 'xinxquanbian'], ['epic']],
    xinx_jiangzhuo: ["female", "xing", 3, ['xinxzengren', 'xinxshunhua'], ['epic']],
    xinx_lvmeng: ["male", "wu", 4, ['xinxbaiyi', 'xinxtaoyin'], ["border:xing", 'epic']],
    xinx_lvlingqi: ["female", "qun", 3, ['xinxfeiyan', 'xinxciyou'], ['legend']],
    xinx_zengao: ["male", "xing", 3, ['xinxjishi', 'xinxxinlue'], ['epic']],
    xinxying_jiangwei: ["male", "shu", 3, ['xinxhemou', 'xinxweixi'], ["border:wei", 'legend']],
    //xinx_yanghuiyu: ["female", "jin", 3, ['xinxshanjiao', 'xinxhuiyan'], ['epic']],
    xinx_sunshangxiang: ["female", "wu", 3, ['xinxqiansi', 'xinxxiaoling'], ["border:xing", 'legend']],
    xinxying_zhonghui: ["male", "wei", 3, ['xinxquanpao', 'xinxqingqiang'], ["border:qun", 'legend']],
    xinx_lvbu: ["male", "qun", 4, ['xinxxuanxiao', 'xinxshiji'], ['epic']],
    xinx_dongxie: ["female", "qun", 3, ['xinxjiaojue', 'xinxfengyao'], ['legend']],
    xinx_zhangchunhua: ["female", "wei", '2/3', ['xinxzhenying', 'xinxzhebian'], ['hiddenSkill', 'epic']],
    xinx_qinlian: ["female", "xing", 3, ['xinxzhiyi', 'xinxshenai'], ['legend']],
    xinxzhu_zhangliao: ["male", "qun", 4, ['xinxyingqi', 'xinxyanhui'], ['legend']],
    xinx_simazhao: ["male", "wei", 3, ['xinxqueyi', 'xinxshexin', 'xinxjinmian'], ['legend']],
    xinxzhu_caocao: ["male", "qun", 4, ['xinxxishuo', 'xinxhaopo'], ['legend']],
    xinxzhu_zhouyu: ["male", "wu", 3, ['xinxqiyi', 'xinxfanjian'], ['legend']],
    xinxying_simayi: ["male", "wei", 3, ['xinxyuanyan', 'xinxchengshu'], ['legend']],
    xinxzhu_zhaoyun: ["male", "qun", 4, ['xinxlongxiang', 'xinxcangnuo'], ['legend']],
    xinx_dongzhuo: ["male", "qun", 4, ['xinxlujing', 'xinxzisui'], ['epic']],
    xinx_wangyun: ["male", "qun", 3, ['xinxjinjie', 'xinxyunjue'], ['epic']],
    xinx_xurong: ["male", "qun", 4, ['xinxjieshuo', 'xinxhuolu'], ['legend']],
    xinx_zhugedan: ["male", "wei", 4, ['xinxkejing', 'xinxjuyi'], ['epic']],
    //xinx_moqiongshu: ["female", "wei", 3, ['xinxchanyi'], ['epic']],
    xinxzhu_simashi: ["male", "wei", 4, ['xinxsanshi', 'xinxchenlue'], ['legend']],
    xinxnew_zhonghui: {
        sex: "male",
        group: "wei",
        hp: 4,
        img: "extension/永夜之境/image/xinx_zhonghui.png",
        trashBin: ["border:qun", 'legend'],
        skills: ['xinxnewquanmou', 'xinxnewwugui'],
    },
    xinxzhu_sunshangxiang: ["female", "wu", 4, ['xinxsaran', 'xinxnigong'], ['legend']],
    xinx_yanrou: ["male", "wei", 4, ['xinxshibei'], ['legend']],
    xinxzhu_liubei: ["male", "qun", 4, ['xinxlianlin'], ['epic']],
    //xinx_dengai: ["male", "wei", 4, [], ['epic']],
    xinxzhu_hanfu: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/xinxzhu_hanfu.png",
        trashBin: ['legend'],
        skills: ['xinxcongfeng', 'xinxchouhuang'],
        dieAudios: ["clan_hanfu"],
    },
    /* xinx_duyu: {
        sex: "male",
        group: "jin",
        hp: 4,
        img: "extension/永夜之境/image/xinxhj_sp_duyu.png",
        trashBin: ['legend'],
        skills: [],
        dieAudios: ["sp_duyu"],
    }, */
    //xinx_qinxi: ["female", "xing", 3, ['xinxxiangfu'], ['legend']],
    //xinx_zoushi: ["female", "qun", 3, ['paowangque', 'paoshiyi'], ['epic'], ["forbidai"]],
    // xinx_yuanshao: ["male", "qun", 4, [], ['epic'],["forbidai"]],
    // xinx_chengong: ["male", "qun", 3, [], ['epic'],["forbidai"]],
    // xinx_caoshuang: ["male", "wei", 4, [], ['epic'],["forbidai"]],
    // xinx_bailingyun: ["female", "wei", 3, [], ['epic'],["forbidai"]],
};

//永夜之始
export const xinx2Character = {
    xinxhy_qiong: {
        sex: "male",
        group: "xinx",
        hp: 4,
        img: "extension/永夜之境/image/xinxhy_qiong.png",
        trashBin: ['legend'],
        skills: ['xinxshuangjian', 'xinxtongxing'],
        dieAudios: ['xinx_qiong'],
    },
    xinx_liuying: {
        sex: "female",
        group: "xinx",
        hp: 4,
        img: "extension/永夜之境/image/xinx_liuying.png",
        trashBin: ['legend'],
        skills: ['xinxyingshi', 'xinxxinzhui'],
    },
    xinx_jingliu: ["female", "xinx", 4, ['xinxxiaguang', 'xinxshuohua'], ['legend']],
    xinx_ren: ["male", "xinx", 5, ['xinxzhili', 'xinxfandu'], ['legend']],
    //开拓者
    xinx_qiong: ["male", "xinx", 3, ['xinxkaituo'], ['legend']],
    xinx_qiong_shadow1: ["male", "xinx", 4, ['xinxhuanling', 'xinxcilian'], ["unseen", "sex:male_castrated"]],
    xinx_qiong_shadow2: ["male", "xinx", 4, ['xinxjizou', 'xinxmengxing'], ["unseen", "sex:male_castrated"]],
    xinx_qiong_shadow3: ["male", "xinx", 4, ['xinxzhupo', 'xinxyanqiang'], ["unseen", "sex:male_castrated"]],
    xinx_mimi: ["female", "xinx", 3, ['xinxhuoban'], ["unseen", "sex:male_castrated", 'legend']],
    xinx_Pollux: ["female", "xinx", 4, ['xinxhuiyi'], ["unseen", "sex:male_castrated", 'legend']],
    xinx_yinglang: ["female", "xinx", 3, ['xinxpojie', 'xinxhairu'], ['epic']],
    xinx_xiadie: ["female", "xinx", 3, ['xinxxsusheng', 'xinxxmingxi'], ['legend']],
    xinx_huangquan: ["female", "xinx", 4, ['xinxleizhi', 'xinxcanmeng', 'xinxjizhen'], ['legend']],
    xinx_luocha: ["male", "xinx", 4, ['xinxyunjiu', 'xinxjiangxing'], ['epic']],
    xinx_fuxuan: ["female", "xinx", 3, ['xinxqiongguan', 'xinxgeze'], ['epic']],
    xinx_yinyuejun: ["male", "xinx", 3, ['xinxkangxin', 'xinxzhuoshi'], ['legend']],
    xinx_daheita: ["female", "xinx", 3, ['xinxjiegou', 'xinxlinggan'], ['legend']],
    xinx_feixiao: ["female", "xinx", 4, ['xinxjueying', 'xinxzhuodeng'], ['legend']],
    xinx_guinaifen: ["female", "xinx", 4, ['xinxduoyi', 'xinxbashi'], ['legend']],
    xinxmeng_liuying: ["female", "xinx", 3, ['xinxyueding'], ['legend']],
    xinx_baie: ["male", "xinx", "4/5", ['xinxzhuhuo', 'xinxfushi'], ['legend']],
    xinx_fengjin: ["female", "xinx", 3, ['xinxtianqi', 'xinxhongzhu'], ['epic']],
    xinx_changyeyue: ["female", "xinx", 3, ['xinxyiyu', 'xinxbuli'], ['epic']],
    xinx_xing: ["female", "xinx", 3, ['xinxzhanshu', 'xinxdashi'], ['legend']],

    xinx_zhigengniao: ["female", "xinx", 3, ['xinxliuguang'], ['legend']],
    xinx_huahuo: ["female", "xinx", 3, ['xinxhuaqianyi'], ['epic']],
    xinx_xilian: ["female", "xinx", 3, ['xinxyilian'], ['legend']],
    // xinx_luanpo: ["female", "xinx", 3, [], ['epic']],
    // xinx_ruanmei: ["female", "xinx", 3, [], ['epic']],
    xinx_xingqiri: ["male", "xinx", 3, ['xinxangang', 'xinxxunji'], ['epic']],
    xinx_xier: ["female", "xinx", 4, ['xinxguiren', 'xinxzaixian'], ['epic']],
    xinx_buluoniya: ["female", "xinx", 4, ['xinxxianji', 'xinxkejie'], ['epic']],
    //xinx_tilixibiesi: ["female", "xinx", 3, [], ['legend']],
    xinx_kafuka: ["female", "xinx", 3, ['xinxmosuo', 'xinxbeichan'], ['epic']],
    //xinx_wangguiren: ["female", "xinx", 3, [], ['legend']],
    //xinx_tuopa: ["female", "xinx", 3, [], ['epic']],
    //xinx_hanya: ["female", "xinx", 3, [], ['rare']],
    xinx_sikeke: ["female", "qun", 4, ['xinxzhuiyuan', 'xinxliuduan'], ["border:xinx", 'legend']],
    xinx_yeshunguang: ["female", "qun", 4, ['xinxmingxin', 'xinxguichen', 'xinxlingxiao'], ["border:xinx", 'legend']],
    xinxnew_liuying: ["female", "xinx", 3, ['xinxnewxinzhui', 'xinxnewyingshi'], ['legend']],
    xinx_tenghuang: ["male", "xinx", "4/6", ['xinxzhengrong', 'xinxbahuang'], ['epic']],
    xinx_xiao: ["female", "xing", 4, ['xinxxuanren', 'xinxcuiren'], ['legend']],
    xinx_aimisi: ["female", "qun", 3, ['xinxsuyin', 'xinxxinshi'], ["border:xinx", 'legend']],
    xinx_yixuan: ["female", "qun", 4, ['xinxxuanmo', 'xinxmiesui'], ["border:xinx", 'legend']],
    xinx_sanyueqi: ["female", "xinx", 4, ['xinxxiexing', 'xinxmiqiong'], ['epic']],
    xinx_dalihua: ["female", "xinx", 4, ['xinxfenshen', 'xinxlianxin'], ['epic']],
    xinx_heitiane: ["female", "xinx", 3, [], ["unseen", 'epic']],
    //xinx_saifeier: ["female", "xinx", 3, ['xinxjiaotu', 'xinxhuanri'], ['epic']],
    xinx_kelvdela: ["female", "xinx", 3, ['xinxfengjue', 'xinxzhengfu'], ['rare']],
    xinx_haiseyin: ["female", "xinx", 4, ['xinxanliu', 'xinxjiange'], ['epic']],//, 'smyyingshi'
    xinx_luka: ["male", "xinx", 4, ['xinxangyang', 'xinxbuxiu'], ['epic']],
    xinx_yinlang999: ["female", "xinx", 4, ['xinxcaidan', 'xinxzunlin'], ['legend']],
    xinx_huohua: ["female", "xinx", 4, ['xinxkuanghuan', 'xinxzhumu'], ['epic']],
    xinx_feiying: ["female", "xinx", 4, ['xinxliaopan', 'xinxwushe'], ['legend']],
    xinx_yaoguang: ["female", "xinx", 3, ['xinxhongji', 'xinxpoju'], ['epic']],
    //xinxzhu_sanyueqi: ["female", "xinx", 4, [], ['epic']],
    //xinx_laite: ["male", "qun", 4, [], ["border:xinx",'legend']],
};

//风雨如晦
export const xinxfengyuCharacter = {
    fyrh_huanggai: {
        sex: "male",
        group: "wu",
        hp: 4,
        trashBin: ['epic'],
        skills: ['fyrhfenge'],
        dieAudios: ['sb_huanggai'],
    },
    fyrh_zhuyi: {
        sex: "male",
        group: "wu",
        hp: 4,
        img: "image/character/zhuji.jpg",
        trashBin: ['epic'],
        skills: ['fyrhkunzhao', 'fyrhranzhong'],
        dieAudios: ["zhuji"],
    },
    fyrhtang_yuanshao: {
        sex: "male",
        group: "qun",
        hp: 4,
        trashBin: ['legend'],
        skills: ['fyrhjuntuan', 'fyrhkuozhang'],
        dieAudios: ['sb_huangyueying'],
    },
    fyrhtang_xuzhu: {
        sex: "male",
        group: "wei",
        hp: 4,
        img: "extension/永夜之境/image/fyrhtang_xuzhu.png",
        trashBin: ['legend'],
        skills: ['fyrhboji'],
        dieAudios: ['shen_xuzhu'],
    },
    fyrhp_changyeyue: {
        sex: "female",
        group: "xinx",
        hp: 3,
        img: "extension/永夜之境/image/fyrhp_changyeyue.png",
        trashBin: ['legend'],
        skills: ['fyrhpwangque', 'fyrhpshiyi'],
        dieAudios: ['xinx_changyeyue'],
    },
    xinx_hanzhuo: ["male", "qun", 6, ['xinxfenjiao'], ['epic']],
    xinx_zhuowenjun: ["female", "shu", 3, ['xinxxiangfu', 'xinxyixin'], ['legend']],
    xinx_limu: ["male", "qun", 4, ['xinxsijiao'], ['epic']],
    xinx_xunguan: ["female", "jin", 4, ['xinxyuwei'], ['legend']],
    xinx_wuqi: ["male", "qun", 4, ['xinxcongzu', 'xinxyibian', 'xinxbailian'], ['legend']],
    xinx_wangmang: ["male", "qun", 4, ['xinxqingding', 'fyrhjianji'], ['rare']],
    xinx_wuyuan: ["male", "qun", 4, ['xinxyuanyuan'], ['rare']],
    xinx_lingfeng: ["male", "wu", 4, ['xinxjilang'], ['epic']],
    xinx_zhugejing: ["male", "wu", 3, ['xinxsian', 'xinxsizhan', 'xinxsitui'], ['legend']],
    xinx_lizhaoyi: {
        sex: "female",
        group: "shu",
        hp: 3,
        img: "extension/永夜之境/image/xinx_lizhaoyi.png",
        trashBin: ['legend'],
        skills: ['fyrhzhiwen', 'fyrhminnian', 'fyrhfenjue'],
        dieAudios: ["clan_xuncai"],
    },
    fyrh_leisai: ["female", "qun", 4, ['fyrhlihua', 'fyrhhuohuan'], ['border:xinx', 'epic']],
    fyrh_dianci: ["male", "qun", 4, ['fyrhzaoju', 'fyrhchongsheng'], ['border:xinx', 'legend']],
    fyrh_zaochuanqiu: ["male", "qun", 4, ['fyrhkeng'], ['border:xinx', 'legend']],
    fyrh_yuanchen: ["male", "shu", 4, ['fyrhzhansui', 'fyrhxiaoxian'], ['legend']],
    fyrh_jiye: ["female", "qun", 4, ['fyrhyouling', 'fyrhxianji'], ['border:xinx', 'rare']],
    fyrh_duyu: ["male", "jin", 4, ['fyrhzhenzhan', 'fyrhpozhu'], ['legend']],
    fyrh_caocao: ["male", "qun", 4, ['fyrhyulie', 'fyrhwenjue'], ['legend']],
    fyrh_jiangwei: ["male", "shu", 4, ['fyrhjizhi', 'fyrhzhiji'], ['legend']],
    fyrh_xuyou: ["male", "qun", 3, ['fyrhchenglue', 'fyrhshicai'], ['epic']],
    fyrh_zhaoyun: {
        sex: "male",
        group: "shu",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_zhaoyun.png",
        trashBin: ['rare'],
        skills: ['fyrhlongdan', 'fyrhyajiao'],
        dieAudios: ["jsrg_zhaoyun"],
    },
    fyrh_chenqun: {
        sex: "male",
        group: "wei",
        hp: 3,
        img: "extension/永夜之境/image/fyrh_chenqun.png",
        trashBin: ['legend'],
        skills: ['fyrhyinzhi', 'fyrhquanxin'],
        dieAudios: ["clan_chenqun"],
    },
    fyrh_bianrang: ["male", "qun", 4, ['fyrhzhanghua', 'fyrhyanfeng'], ['legend']],
    fyrh_zuti: {
        sex: "male",
        group: "jin",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_zuti.png",
        trashBin: ['legend'],
        skills: ['fyrhjiji'],
        dieAudios: ["litong"],
    },
    fyrh_lvzhi: ["female", "qun", 3, ['fyrhjunce'], ['epic']],
    fyrh_anbian: ["male", "qun", 4, ['fyrhruiqi'], ['border:xinx', 'legend']],
    fyrh_yuji: ["female", "qun", 3, ['fyrhquxing', 'fyrhwulan'], ['legend']],
    fyrh_weiqinghuoqubing: ["male", "qun", 4, ['fyrhjuemo'], ['epic']],
    xinxhj_fyrh_weiqinghuoqubing: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_weiqinghuoqubing.png",
        trashBin: ['epic'],
        skills: ['oldfyrhjuemo'],
        dieAudios: ["fyrh_weiqinghuoqubing"],
    },
    fyrh_pengyue: ["male", "qun", 5, ['fyrhliebing', 'fyrhnaoji'], ['legend']],
    fyrh_chentang: ["male", "qun", 5, ['fyrhjiaobing'], ['legend']],
    fyrh_chenping: ["male", "qun", 3, ['fyrhjiedu', 'fyrhyouren'], ['epic']],
    fyrh_goujian: ["male", "qun", 6, ['fyrhtoulao'], ['rare']],
    fyrh_guanyu: {
        sex: "male",
        group: "shu",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_guanyu.png",
        trashBin: ['legend'],
        skills: ['fyrhwusheng', 'fyrhyijue'],
        dieAudios: ["re_guanyu"],
    },
    fyrh_liumin: ["male", "shu", 3, ['fyrhyizuo', 'fyrhlianzhi'], ['epic']],
    fyrh_qiangzhiemo: ["male", "qun", 4, ['fyrhshitang'], ['border:xinx', 'legend']],
    fyrh_wangping: ["male", "shu", 4, ['fyrhyizhen', 'fyrhzhibing'], ['epic']],
    fyrh_zhangfei: ["male", "shu", 4, ['fyrhyafeng', 'fyrhbaohe'], ['epic']],
    fyrh_guyu: ["male", "wu", 4, ['fyrhtuilang'], ['epic']],
    fyrhbl_zhouyu: ["male", "wu", 4, ['fyrhyingzi', 'fyrhbingfa'], ['epic']],
    fyrh_xieqi: ["male", "wei", 4, ['fyrhrangrang'], ['rare']],
    fyrh_jiachong: ["male", "jin", 3, ['fyrhxilong', 'fyrhzuiwo'], ['legend']],
    fyrh_xujing: {
        sex: "male",
        group: "shu",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_xujing.png",
        trashBin: ['epic'],
        skills: ['fyrhxuqi', 'fyrhzhiqi'],
        dieAudios: ["dc_xujing"],
    },
    fyrh_fazheng: {
        sex: "male",
        group: "shu",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_fazheng.png",
        trashBin: ['epic'],
        skills: ['fyrhyazi', 'fyrhxuanmi'],
        dieAudios: ["sb_fazheng"],
    },
    fyrh_zhenfu: {
        sex: "female",
        group: "wei",
        hp: 3,
        img: "extension/永夜之境/image/fyrh_zhenfu.png",
        trashBin: ['epic'],
        skills: ['fyrhluoshen', 'fyrhlenzen'],
        dieAudios: ["sb_zhenji"],
    },
    fyrh_huaxiong: ["male", "qun", 6, ['fyrhyaowu'], ['rare']],
    fyrh_zhengxiaotong: ["male", "wei", 4, ['fyrhxiushen', 'fyrhbaiwei'], ['legend']],
    fyrh_dengai: {
        sex: "male",
        group: "wei",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_dengai.png",
        trashBin: ['legend'],
        skills: ['fyrhzaoxian', 'fyrhtuntian'],
        dieAudios: ["pot_dengai"],
    },
    fyrh_luxun: {
        sex: "male",
        group: "wu",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_luxun.png",
        trashBin: ['legend'],
        skills: ['fyrhzhuying'],
        dieAudios: ["dc_sb_luxun"],
    },
    fyrh_weijie: {
        sex: "male",
        group: "jin",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_weijie.png",
        trashBin: ['legend'],
        skills: ['fyrhlunxuan', 'fyrhkansha'],
    },
    fyrh_shiyiguang: ["female", "qun", 3, ['fyrhlian', 'fyrhsu'], ['legend']],
    fyrh_zhangliao: {
        sex: "male",
        group: "wei",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_zhangliao.png",
        trashBin: ['legend'],
        skills: ['fyrhtuxi', 'fyrhzhiti'],
        dieAudios: ["clan_wuban"],
    },
    fyrh_jiaerjiali: ["male", "qun", 4, ['fyrhroubo', 'fyrhmianshu'], ['border:xinx', 'legend']],
    fyrh_yanyan: {
        sex: "male",
        group: "shu",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_yanyan.png",
        trashBin: ['epic'],
        skills: ['fyrhjuzhan', 'fyrhqingye'],
        dieAudios: ["yanyan"],
    },
    fyrh_simaying: {
        sex: "male",
        group: "jin",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_simaying.png",
        trashBin: ['epic'],
        skills: ['fyrhbianshi', 'fyrhege'],
    },
    fyrh_caozhi: {
        sex: "male",
        group: "wei",
        hp: 3,
        img: "extension/永夜之境/image/fyrh_caozhi.png",
        trashBin: ['epic'],
        skills: ['fyrhjiushi', 'fyrhluoying'],
    },
    fyrh_wangling: {
        sex: "male",
        group: "wei",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_wangling.png",
        trashBin: ['epic'],
        skills: ['fyrhjidang', 'fyrhzifu'],//, 'smyyingshi'
        dieAudios: ["wangling"],
    },
    fyrh_fengxizhangnan: {
        sex: "male",
        group: "shu",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_fengxizhangnan.png",
        trashBin: ['legend'],
        skills: ['fyrhxiejian', 'fyrhpijing'],
    },
    fyrh_qinwuyang: {
        sex: "male",
        group: "qun",
        hp: 5,
        img: "extension/永夜之境/image/fyrh_qinwuyang.png",
        trashBin: ['legend'],
        skills: ['fyrhbawu', 'fyrhweijie'],
    },
    fyrh_zhangxiu: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_zhangxiu.png",
        trashBin: ['epic'],
        skills: ['fyrhfujie', 'fyrhxuzhong'],
    },
    fyrh_chendao: {
        sex: "male",
        group: "shu",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_chendao.png",
        trashBin: ['epic'],
        skills: ['fyrhwanglie'],
        dieAudios: ["pot_chendao"],
    },
    fyrh_zhugejun: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_zhugejun.png",
        trashBin: ['epic'],
        skills: ['fyrhgenghuang', 'fyrhbisao', 'fyrhshouzhen'],
        dieAudios: ["dc_zhugejun"],
    },
    fyrh_wangcheng: {
        sex: "male",
        group: "jin",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_wangcheng.png",
        trashBin: ['epic'],
        skills: ['fyrhweiyu', 'fyrhmobei'],
        dieAudios: ['re_fazheng'],
    },
    fyrh_qinhui: {
        sex: "male",
        group: "qun",
        hp: 3,
        img: "extension/永夜之境/image/fyrh_qinhui.png",
        trashBin: ['epic'],
        skills: ['fyrhchuailing', 'fyrhhufu'],
        dieAudios: ["chengui"],
    },
    fyrh_dailaidongzhu: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_dailaidongzhu.png",
        trashBin: ['rare'],
        skills: ['fyrhjiaxie', 'fyrhcangren'],
        dieAudios: ["mengyou"],
    },
    fyrh_liuyan: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_liuyan.png",
        trashBin: ['epic'],
        skills: ['fyrhlietu', 'fyrhkuizong'],
        dieAudios: ["liuyan"],
    },
    xinxhj_fyrh_liuyan: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/xinxhj_fyrh_liuyan.png",
        trashBin: ['epic'],
        skills: ['fyrhlietu', 'fyrhkuizong'],
        dieAudios: ["liuyan"],
    },
    fyrh_zhangjiao: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_zhangjiao.png",
        trashBin: ['epic'],
        skills: ['fyrhyijin', 'fyrhhuangsheng', 'fyrhcanjue'],
        dieAudios: ["re_zhangjiao"],
    },
    fyrh_maxiumatie: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "image/character/maxiumatie.jpg",
        trashBin: ['rare'],
        skills: ['fyrhquxian', 'fyrhjiaoshi'],
        dieAudios: ["maxiumatie"],
    },
    fyrh_weiyi: {
        sex: "male",
        group: "jin",
        hp: 4,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/fyrh_weiyi.png",
        skills: ['fyrhliecheng'],
        dieAudios: ['xinx_lvbu'],
    },
    fyrhxiu_zhaoyun: {
        sex: "male",
        group: "shu",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrhxiu_zhaoyun.png",
        skills: ['fyrhfuzhi', 'fyrhshunyi'],
        dieAudios: ['xinxzhu_zhaoyun'],
    },
    fyrh_simayi: {
        sex: "male",
        group: "wei",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/xinxying_simayi.png",
        skills: ['fyrhruluo', 'fyrhneiji'],
        dieAudios: ['xinxying_simayi'],
    },
    fyrh_gouxi: {
        sex: "male",
        group: "jin",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrh_gouxi.png",
        skills: ['fyrhchicui', 'fyrhhuanhuo'],
        dieAudios: ['db_wenyang'],
    },
    fyrh_simashao: {
        sex: "male",
        group: "jin",
        hp: 4,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/fyrh_simashao.png",
        skills: ['fyrhjiabai'],
        dieAudios: ['jin_jsrg_simazhao'],
    },
    fyrh_daheita: {
        sex: "female",
        group: "xinx",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrh_daheita.png",
        skills: ['fyrhpouxi'],
        dieAudios: ['xinx_daheita'],
    },
    fyrh_changyeyue: {
        sex: "female",
        group: "xinx",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrh_changyeyue.png",
        skills: ['fyrhmenglong'],
    },
    fyrh_xilian: {
        sex: "female",
        group: "xinx",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrh_xilian.png",
        skills: ['fyrhningxi'],
        dieAudios: ['xinx_xilian'],
    },
    fyrh_fuxuan: {
        sex: "female",
        group: "xinx",
        hp: 3,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/fyrh_fuxuan.png",
        skills: ['fyrhpitai', 'fyrhjishen'],
        dieAudios: ['xinx_fuxuan'],
    },
    fyrh_huahuo: {
        sex: "female",
        group: "xinx",
        hp: 3,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/fyrh_huahuo.png",
        skills: ['fyrhqianyi'],
        dieAudios: ['xinx_huahuo'],
    },
    fyrh_liuying: {
        sex: "female",
        group: "xinx",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrh_liuying.png",
        skills: ['fyrhfuhuo', 'fyrhzhuguang'],
        dieAudios: ['xinx_liuying'],
    },
    fyrhold_huahuo: {
        sex: "female",
        group: "xinx",
        hp: 3,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/fyrhold_huahuo.png",
        skills: ['oldfyrhqianyi'],
        dieAudios: ['xinx_huahuo'],
    },
    fyrhu_haozhao: {
        sex: "male",
        group: "wei",
        hp: 4,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/fyrhu_haozhao.png",
        skills: ['fyrhzhengu'],
        dieAudios: ['haozhao'],
    },
    fyrhu_machao: {
        sex: "male",
        group: "qun",
        hp: 4,
        trashBin: ['epic'],
        img: "extension/永夜之境/image/fyrhu_machao.png",
        skills: ['fyrhzhuiming'],
        dieAudios: ['sp_machao'],
    },
    fyrh_zhuangfangyi: {
        sex: "female",
        group: "qun",
        groupBorder: "xinx",
        hp: 3,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/fyrh_zhuangfangyi.png",
        skills: ['fyrhchunleidong', 'fyrhwanwusheng'],
    },
    fyrhu_tongyuan: {
        sex: "male",
        group: "qun",
        hp: 4,
        trashBin: ['epic'],
        img: "image/character/xia_tongyuan.jpg",
        skills: ['fyrhchaofeng'],
        dieAudios: ['xia_tongyuan'],
    },
    fyrhu_wuxian: {
        sex: "female",
        group: "shu",
        hp: 3,
        trashBin: ['epic'],
        img: "extension/永夜之境/image/fyrhu_wuxian.png",
        skills: ['fyrhyirong', 'clanmuyin'],
        tempname: ["clan_wuxian"],
        dieAudios: ['clan_wuxian'],
    },
    fyrh_kelvdela: {
        sex: "female",
        group: "xinx",
        hp: 3,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/fyrh_kelvdela.png",
        skills: ['fyrhranlv', 'fyrhchongsu'],
        dieAudios: ['xinx_kelvdela'],
    },
    fyrhu_lvbu: {
        sex: "male",
        group: "qun",
        hp: 5,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/fyrhu_lvbu.png",
        skills: ['fyrhwuqian'],
        dieAudios: ['xinx_lvbu'],
    },
    fyrhu_sunquan: {
        sex: "male",
        group: "wu",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrhu_sunquan.png",
        skills: ['fyrhminglv', 'fyrhzihun'],
        dieAudios: ['v_sunquan'],
    },
    fyrhu_zhugedan: {
        sex: "male",
        group: "wei",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrhu_zhugedan.png",
        skills: ['fyrhjuyi'],
        dieAudios: ['xinx_zhugedan'],
    },
    fyrhu_zhonghui: {
        sex: "male",
        group: "wei",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrhu_zhonghui.png",
        skills: ['fyrhyuzhi'],
        dieAudios: ['clan_zhonghui'],
    },
    fyrhu_zhengxuan: {
        sex: "male",
        group: "qun",
        hp: 3,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrhu_zhengxuan.png",
        skills: ['fyrhzhengjing'],
        dieAudios: ['huangchengyan'],
    },
    fyrh_haopu: {
        sex: "male",
        group: "shu",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrh_haopu.png",
        skills: ['fyrhjicheng'],
        dieAudios: ['haopu'],
    },
    fyrhxiu_jiangwei: {
        sex: "male",
        group: "shu",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrhxiu_jiangwei.png",
        skills: ['fyrhzhuyang'],
        tempname: ["ol_sb_jiangwei"],
        dieAudios: ['ol_sb_jiangwei'],
    },
    fyrh_sunchen: {
        sex: "male",
        group: "wu",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrh_sunchen.png",
        skills: ['fyrhxiongduan'],
        dieAudios: ['pot_sunchen'],
    },
    fyrh_caozhao: {
        sex: "male",
        group: "wei",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrh_caozhao.png",
        skills: ['fyrhxixi'],
        dieAudios: ['heyan'],
    },
    fyrh_gongsunli: {
        sex: "female",
        group: "qun",
        groupBorder: "xinx",
        hp: 3,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/fyrh_gongsunli.png",
        skills: ['fyrhpaoleidi', 'fyrhpaohuanhun'],
    },
    fyrh_wanglang: {
        sex: "male",
        group: "qun",
        groupBorder: "xinx",
        hp: 3,
        img: "extension/永夜之境/image/fyrh_wanglang.png",
        trashBin: ['legend'],
        skills: ['fyrhhyygushe', 'fyrhhyyzuobao'],
        dieAudios: ["wanglang"],
    },
    fyrhy_fugu: {
        sex: "male",
        group: "wei",
        hp: 3,
        img: "extension/永夜之境/image/fyrhy_fugu.png",
        trashBin: ['epic'],
        skills: ['fyrhligang', 'fyrhkenjian'],
        dieAudios: ['dc_dongzhao'],
    },
    fyrh_xusheng: {
        sex: "male",
        group: "wu",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_xusheng.png",
        trashBin: ['epic'],
        skills: ['fyrhyicheng'],
    },
    fyrh_liyuanba: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/fyrh_liyuanba.png",
        trashBin: ['legend'],
        skills: ['fyrhwuji'],
    },
    fyrhtang_zhugeliang: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/fyrhtang_zhugeliang.png",
        trashBin: ['legend'],
        skills: ['fyrhcangzhuo'],
        dieAudios: ['friend_zhugeliang'],
    },
    fyrhtang_huangyueying: {
        sex: "female",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/fyrhtang_huangyueying.png",
        trashBin: ['legend'],
        skills: ['fyrhtanghufu'],
        dieAudios: ['sb_huangyueying'],
    },
    


};

//武将修改
export const xinxhuaijiuCharacter = {
    xinxhjylyg_xuhuang: {
		sex: "male",
		group: "wei",
		hp: 4,
        trashBin: ['rare'],
		skills: ["xinxhjyl_duanliang", "xinxhjyl_zier"],
        dieAudios: ["sb_xuhuang"],
	},
    xinxhj_guigu: {
		sex: "male",
		group: "qun",
		hp: 5,
        trashBin: ['rare'],
        img: "image/character/hm_guigu.jpg",
		skills: ["xinxhj_tuntian", "xinxhj_qianjun"],
        dieAudios: ["sb_yuanshao"],
	},
    xinxhj_xushao: {
		sex: "male",
		group: "qun",
		hp: 4,
        trashBin: ['legend'],
		skills: ["xinxhjpingjian"],
        dieAudios: ["xushao"],
	},
    xinxhj_clan_xunchen: {
        sex: "male",
        group: "qun",
        hp: 3,
        trashBin: ['rare'],
        img: "image/character/clan_xunchen.jpg",
        skills: ["xinxhjsankuang", "xinxhjbeishi", "clandaojie"],
        clans: ["颍川荀氏"],
        tempname: ["clan_xunchen"],
        dieAudios: ["clan_xunchen"],
    },
    xinxhj_star_zhanghe: {
        sex: "male",
        group: "qun",
        hp: 4,
        trashBin: ['rare'],
        img: "image/character/star_zhanghe.jpg",
        skills: ["xinxhjjunxi", "xinxhjjixian"],
        dieAudios: ["star_zhanghe"],
    },
    xinxhj_yuji: {
        sex: "male",
        group: "qun",
        hp: 3,
        img: "image/character/pot_yuji.jpg",
        trashBin: ['epic'],
        skills: ["xinxhjdaozhuan", "xinxhjfuji"],
        tempname: ["pot_yuji"],
        dieAudios: ["pot_yuji"],
    },
    xinxhj_zhanghuai: {
        sex: "female",
        group: "wu",
        hp: 3,
        img: "image/character/zhanghuai.jpg",
        trashBin: ['rare'],
        skills: ['xinxhjlaoyan', 'xinxhjjueyan'],
        dieAudios: ["zhanghuai"],
    },
    xinxhj_sb_lvbu: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "image/character/sb_lvbu.jpg",
        trashBin: ['epic'],
        skills: ['xinxhjsbwushuang', 'xinxhjsbliyu'],
        dieAudios: ["sb_lvbu"],
    },
    xinxhj_dc_sb_luxun: {
        sex: "male",
        group: "qun",
        hp: 3,
        img: "image/character/dc_sb_luxun.jpg",
        trashBin: ['legend'],
        character: ['dc_sb_luxun'],
        tempname: ["dc_sb_luxun"],
        skills: ['xinxhjdcsbjunmou', 'xinxhjdcsbzhanyan'],
        dieAudios: ["dc_sb_luxun"],
    },
    xinxhj_sb_caopi: {
        sex: "male",
        group: "wei",
        hp: 3,
        trashBin: ['legend'],
        img: "image/character/sb_caopi.jpg",
        skills: ['xinxhjxingshang', 'xinxhjfangzhu', 'xinxhjsongwei'],
        isZhugong: true,
        dieAudios: ["sb_caopi"],
    },
    xinxhj_new_simayi: {
        sex: "male",
        group: "shen",
        hp: 4,
        skills: ["xinxhjjilin", "xinxhjyingyou", "xinxhjyingtian"],
        trashBin: ['legend'],
        img: "image/character/new_simayi.jpg",
        dieAudios: ["new_simayi"],
        names: "司马|懿",
    },
    xinxhj_v_zhangliao: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "image/character/v_zhangliao.jpg",
        skills: ["xinxhjdcyuxi", "xinxhjdcporong"],
        trashBin: ["character:v_zhangliao", 'legend'],
        dieAudios: ["v_zhangliao"],
    },
    xinxhj_dc_simashi: {
        sex: "male",
        group: "wei",
        hp: 3,
        img: "image/character/dc_simashi.jpg",
        skills: ["xinxhjdcsanshi", "xinxhjdczhenrao", "xinxhjdcchenlve"],
        names: "司马|师",
        trashBin: ['legend'],
        groupBorder: "jin",
        dieAudios: ["dc_simashi"],
    },
    xinxhj_dc_sb_lvmeng: {
        sex: "male",
        group: "wu",
        hp: 4,
        img: "image/character/dc_sb_lvmeng.jpg",
        skills: ["xinxhjdcsbhengye", "xinxhjdcsbyingbo"],
        trashBin: ['epic'],
    },
    xinxhj_mb_huangzu: {
        sex: "male",
        group: "qun",
        hp: 4,
        trashBin: ['rare'],
        img: "image/character/mb_huangzu.jpg",
        skills: ["xinxhjmbchizhang", "xinxhjmbduanyang"],
        dieAudios: ["mb_huangzu"],
    },
    xinxhj_mb_huangzu: {
        sex: "male",
        group: "qun",
        hp: 4,
        trashBin: ['rare'],
        img: "image/character/mb_huangzu.jpg",
        skills: ["xinxhjmbchizhang", "xinxhjmbduanyang"],
        dieAudios: ["mb_huangzu"],
    },
    xinxhj_dc_sb_jushou: {
        sex: "male",
        group: "qun",
        hp: 3,
        trashBin: ['rare'],
        img: "image/character/dc_sb_jushou.jpg",
        skills: ["xinxhjzuojun", "xinxhjmuwang"],
        dieAudios: ["dc_sb_jushou"],
    },
    xinxhj_yj_sb_guojia: {
        sex: "male",
        group: "wei",
        hp: 3,
        img: "image/character/yj_sb_guojia.jpg",
        trashBin: ["character:yj_sb_guojia", 'legend'],
        skills: ["xinxhjxianmou", "xinxhjlunshi"],
        dieAudios: ["yj_sb_guojia"],
    },
    xinxhj_dc_xiahouxuan: {
        sex: "male",
        group: "wei",
        hp: 3,
        img: "image/character/dc_xiahouxuan.jpg",
        trashBin: ['legend'],
        skills: ["xinxhjboxuan", "xinxhjyizheng", "xinxhjguilin"],
        names: "夏侯|玄",
        dieAudios: ["dc_xiahouxuan"],
    },
    xinxhj_ol_jsrg_caocao: {
        sex: "male",
        group: "qun",
        hp: 4,
        trashBin: ['legend'],
        img: "image/character/jsrg_caocao.jpg",
        skills: ["xinxhjdingxi", "xinxhjnengchen", "xinxhjhuojie"],
        dieAudios: ["jsrg_caocao"],
    },
    xinxhj_star_fazheng: {
        sex: "male",
        group: "shu",
        hp: 3,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/xinxhj_star_fazheng.png",
        skills: ["xinxhjzhiji", "xinxhjanji"],
        dieAudios: ["star_fazheng"],
    },
    xinxhj_xuwen: {
        sex: "female",
        hp: 3,
        group: "wei",
        trashBin: ['legend'],
        img: "extension/永夜之境/image/xinxhj_xuwen.png",
        skills: ["xinxhjfuhui", "xinxhjmohua"],
        dieAudios: ["xuwen"],
    },
    xinxhj_dc_zhushuo: {
        sex: "male",
        group: "wei",
        trashBin: ['epic'],
        hp: 4,
        img: "image/character/dc_zhushuo.jpg",
        skills: ["xinxhjzsshuhe", "xinxhjjilie"],
        dieAudios: ["dc_zhushuo"],
    },
    xinxhj_liujinliupei: {
        sex: "female",
        group: "wei",
        hp: 3,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/xinxhj_liujinliupei.png",
        skills: ["xinxhjqixin", "xinxhjjiusi"],
        names: "刘|衿-刘|佩",
        dieAudios: ["liujinliupei"],
    },
    xinxhj_simashi: {
        sex: "male",
        group: "wei",
        hp: 4,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/xinxyin_simashi.png",
        skills: ["xinxhjbaiyi", "xinxhjjinglve", "xinxhjshanli"],
        names: "司马|师",
        groupBorder: "xing",
        dieAudios: ["simashi"],
    },
    xinxhj_sunhuan: {
        sex: "male",
        group: "wu",
        hp: 4,
        trashBin: ['rare'],
        skills: ["xinxhjniji"],
        groupBorder: "xing",
        img: "extension/永夜之境/image/xinxhj_sunhuan.png",
        dieAudios: ["sunhuan"],
    },
    xinxhj_sb_zhangxiu: {
        sex: "male",
        group: "qun",
        hp: 4,
        groupBorder: "xing",
        trashBin: ['rare'],
        img: "extension/永夜之境/image/xinxhj_sb_zhangxiu.png",
        skills: ["xinxhjsbfuxi", "xinxhjsbhaoyi"],
        dieAudios: ["dc_sb_zhangxiu"],
    },
    xinxhj_hefei_zhangliao: {
        sex: "male",
        group: "wei",
        hp: 4,
        groupBorder: "xing",
        trashBin: ['legend'],
        img: "image/character/hefei_zhangliao.jpg",
        skills: ["xinxhjchonglei", "xinxhjdangshi"],
        dieAudios: ["hefei_zhangliao"],
    },
    xinxhj_sp_zhonghui: {
        sex: "male",
        group: "wei",
        hp: 4,
        skills: ["xinxhjsizi", "xinxhjxiezhi", "xinxhjyunan", "xinxhjkechang"],
        img: "extension/永夜之境/image/xinxhj_sp_zhonghui.png",
        isZhugong: true,
        trashBin: ['legend'],
        clans: ["颍川钟氏"],
        doubleGroup: ["wei", "qun"],
    },
    xinxhj_jsrg_zhangliao: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "image/character/ol_jsrg_zhangliao.jpg",
        skills: ["xinxhjzhengbing", "xinxhjtuwei"],
        doubleGroup: ["wei", "qun"],
        trashBin: ['legend'],
        dieAudios: ["jsrg_zhangliao"],
    },
    xinxhj_sb_zhangliao: {
        sex: "male",
        group: "wei",
        hp: 4,
        img: "extension/永夜之境/image/xinxhj_sb_zhangliao.png",
        skills: ["xinxhjtuxi", "xinxhjdengfeng"],
        trashBin: ['epic'],
        dieAudios: ["sb_zhangliao"],
    },
    xinxhj_clan_zhonghui: {
        sex: "male",
        group: "wei",
        hp: 2,
        maxHp: 4,
        img: "image/character/clan_zhonghui.jpg",
        trashBin: ["character:clan_zhonghui", 'legend'],
        skills: ["xinxhjyuzhi", "xinxhjxieshu", "xinxhjbaozu"],
        clans: ["颍川钟氏"],
        dieAudios: ["clan_zhonghui"],
    },
    xinxhj_dc_wuzhi: {
        sex: "male",
        group: "wei",
        hp: 3,
        trashBin: ['rare'],
        img: "image/character/dc_wuzhi.jpg",
        skills: ["xinxhjweiti", "xinxhjyuanrong"],
        dieAudios: ["dc_wuzhi"],
    },
    xinxhj_dc_zhaoxiang: {
        sex: "female",
        group: "shu",
        hp: 4,
        img: "image/character/dc_zhaoxiang.jpg",
        trashBin: ['legend'],
        skills: ["rexinxhjfanghun", "xinxhjfuhan"],
        dieAudios: ["zhaoxiang"],
    },
    xinxhj_sb_wuyi: {
        sex: "male",
        group: "shu",
        hp: 4,
        img: "image/character/dc_sb_wuyi.jpg",
        skills: ["xinxhjsbshibian", "xinxhjsbbibu"],
        dieAudios: ["dc_sb_wuyi"],
        trashBin: ['legend'],
        clans: ["陈留吴氏"],
    },
    xinxhj_guānning: {
        sex: "male",
        group: "shu",
        hp: 3,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/xinxhj_guānning.png",
        skills: ["xinxhjxiuwen", "xinxhjlongsong"],
        dieAudios: ["guānning"],
    },
    xinxhj_wupu: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "image/character/wupu.jpg",
        trashBin: ['rare'],
        skills: ["xinxhjduanti", "xinxhjshicao"],
        dieAudios: ["wupu"],
    },
    xinxhj_hefei_lidian: {
        sex: "male",
        group: "wei",
        hp: 4,
        img: "image/character/hefei_lidian.jpg",
        trashBin: ['rare'],
        skills: ["xinxhjduanjin", "xinxhjgaigong"],
        dieAudios: ["hefei_lidian"],
    },
    xinxhj_hefei_yuejin: {
        sex: "male",
        group: "wei",
        hp: 4,
        trashBin: ['epic'],
        img: "extension/永夜之境/image/xinxhj_hefei_yuejin.png",
        skills: ["xinxhjxianjian", "xinxhjzherui"],
        dieAudios: ["hefei_yuejin"],
    },
    xinxhj_dc_sb_zhouyu: {
        sex: "male",
        group: "wu",
        hp: 4,
        skills: ["xinxhjsbronghuo", "xinxhjsbyingmou"],
        img: "image/character/dc_sb_zhouyu.jpg",
        trashBin: ["character:dc_sb_zhouyu", 'epic'],
        dieAudios: ["dc_sb_zhouyu"],
    },
    xinxhj_luotong: {
        sex: "male",
        group: "wu",
        hp: 4,
        img: "extension/永夜之境/image/xinxhj_luotong.png",
        trashBin: ['epic'],
        skills: ["xinxhjqinzheng"],
        dieAudios: ["luotong"],
    },
    xinxhj_wangyuanji: {
        sex: "female",
        group: "wei",
        hp: 3,
        img: "extension/永夜之境/image/xinxhj_wangyuanji.png",
        skills: ["xinxhjqianchong", "xinxhjshangjian"],
        groupBorder: "jin",
        trashBin: ['epic'],
        character: ["wangyuanji"],
        tempname: ["wangyuanji"],
        dieAudios: ["wangyuanji"],
    },
    xinxhj_yanghuiyu: {
        sex: "female",
        group: "wei",
        hp: 3,
        img: "extension/永夜之境/image/xinxhj_yanghuiyu.png",
        skills: ["xinxhjhongyi", "xinxhjquanfeng"],
        trashBin: ['epic'],
        groupBorder: "jin",
    },
    xinxhj_sp_duyu: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/xinxhj_sp_duyu.png",
        skills: ["xinxhjwuku", "xinxhjsanchen"],
        trashBin: ['legend'],
        groupBorder: "jin",
        dieAudios: ["sp_duyu"],
    },
    xinxhj_sunba: {
        sex: "male",
        group: "wu",
        hp: 4,
        img: "extension/永夜之境/image/xinxhj_sunba.png",
        skills: ["xinxhjjiedang", "xinxhjjidi"],
        trashBin: ['epic'],
        dieAudios: ["sunba"],
    },
    xinxhj_liubian: {
        sex: "male",
        group: "qun",
        hp: 3,
        img: "extension/永夜之境/image/xinxhj_liubian.png",
        skills: ["xinxhjshiyuan", "xinxhjdushi"],
        isZhugong: true,
        trashBin: ['epic'],
        dieAudios: ["liubian"],
    },
    xinxhj_yue_caiyong: {
        sex: "male",
        group: "qun",
        hp: 3,
        img: "extension/永夜之境/image/xinxhj_yue_caiyong.png",
        trashBin: ['epic'],
        skills: ["xinxhjjiaowei", "xinxhjfeibai"],
        dieAudios: ["yue_caiyong"],
    },
    xinxhj_wangkuang: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "extension/永夜之境/image/xinxhj_wangkuang.png",
        trashBin: ['rare'],
        skills: ["xinxhjrenxia"],
        dieAudios: ["wangkuang"],
    },
    xinxhj_jsrg_zhanghe: {
        sex: "male",
        group: "qun",
        hp: 4,
        img: "image/character/ol_jsrg_zhanghe.jpg",
        skills: ["xinxhjqiongtu", "xinxhjxianzhu"],
        trashBin: ['rare'],
        dieAudios: ["jsrg_zhanghe"],
    },
    xinxhj_sb_jiangwei: {
        sex: "male",
        group: "shu",
        hp: 4,
        trashBin: ['epic'],
        img: "extension/永夜之境/image/xinxhj_sb_jiangwei.png",
        skills: ["xinxhjsbzhuri", "xinxhjsbranji"],
        dieAudios: ["ol_sb_jiangwei"],
    },
    xinxhj_ol_qinlang: {
        sex: "male",
        group: "wei",
        hp: 4,
        trashBin: ['epic'],
        img: "extension/永夜之境/image/xinxhj_ol_qinlang.png",
        skills: ["xinxhjxianying"],
        dieAudios: ["ol_qinlang"],
    },
    xinxhj_dongxu: {
        sex: "female",
        group: "qun",
        hp: 3,
        trashBin: ['legend'],
        img: "extension/永夜之境/image/xinxhj_dongxu.png",
        skills: ["xinxhjqingleng", "xinxhjzhendu"],
        dieAudios: ["dongxu"],
    },
    xinxhj_dc_wuban: {
        sex: "male",
        group: "shu",
        hp: 4,
        skills: ['xinxhjyouzhan'],
        trashBin: ['rare'],
        img: "image/character/dc_wuban.jpg",
        clans: ["陈留吴氏"],
    },
    xinxhj_daxiaoqiao: {
        sex: "female",
        group: "wu",
        hp: 3,
        skills: ["xinxhjxingwu", "xinxhjpingting"],
        tempname: ["daxiaoqiao"],
        trashBin: ['rare'],
        img: "image/character/tw_daxiaoqiao.jpg",
        names: "桥|null-桥|null",
        dieAudios: ["daxiaoqiao"],
    },
    xinxhj_bingyuan: {
        sex: "male",
        group: "qun",
        hp: 4,
        trashBin: ['rare'],
        img: "image/character/tw_bingyuan.jpg",
        skills: ["xinxhjbingde", "xinxhjqingtao"],
        dieAudios: ["tw_bingyuan"],
    },
    xinxhj_clan_wuqiao: {
        sex: "male",
        group: "qun",
        hp: 4,
        trashBin: ['rare'],
        img: "image/character/clan_wuqiao.jpg",
        skills: ["xinxhjqiajue", "clanmuyin"],
        clans: ["陈留吴氏"],
        groupBorder: "jin",
        dieAudios: ["clan_wuqiao"],
        character: ["clan_wuqiao"],
        tempname: ["clan_wuqiao"],
    },
    xinxhj_yangzhi: {
        sex: "female",
        group: "jin",
        hp: 3,
        img: "extension/永夜之境/image/xinxhj_yangzhi.png",
        skills: ["xinxhjwanyi", "xinxhjmaihuo"],
        trashBin: ['legend'],
        clans: ["弘农杨氏"],
        dieAudios: ["yangzhi"],
    },
    xinxhj_yangyan: {
        sex: "female",
        group: "jin",
        hp: 3,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/xinxhj_yangyan.png",
        skills: ["xinxhjxuanbei", "xinxhjxianwan"],
        clans: ["弘农杨氏"],
        dieAudios: ["yangyan"],
    },
    xinxhj_ol_lingtong: {
        sex: "male",
        group: "wu",
        hp: 4,
        skills: ["xinxhjxuanfeng"],
        trashBin: ['rare'],
        img: "image/character/ol_lingtong.jpg",
        tempname: ["re_lingtong"],
        dieAudios: ["re_lingtong"],
    },
    xinxhj_mb_shen_machao: {
        sex: "male",
        group: "shen",
        hp: 4,
        trashBin: ['rare'],
        img: "image/character/mb_shen_machao.jpg",
        skills: ["xinxhjyuli", "xinxhjtingwei", "xinxhjjimie"],
        dieAudios: ["mb_shen_machao"],
    },
    xinxhj_caoying: {
        sex: "female",
        group: "wei",
        hp: 4,
        trashBin: ['rare'],
        img: "image/character/caoying.jpg",
        tempname: ["caoying"],
        skills: ["xinxhjlingren", "xinxhjfujian"],
        dieAudios: ["caoying"],
    },
    xinxhj_jushou: {
        sex: "male",
        group: "qun",
        hp: 3,
        //maxHp: 3,
        //hujia: 3
        trashBin: ['rare'],
        img: "extension/永夜之境/image/xinxhj_jushou.png",
        skills: ["xinxhjjianying", "dcshibei"],
        dieAudios: ["xin_jushou"],
    },
    xinxhj_haopu: {
        sex: "male",
        group: "shu",
        hp: 4,
        img: "image/character/haopu.jpg",
        trashBin: ['rare'],
        skills: ["xinxhjzhenying"],
        dieAudios: ["haopu"],
    },
    xinxhj_duanjiong: {
        sex: "male",
        group: "qun",
        hp: 4,
        trashBin: ['rare'],
        img: "image/character/duanjiong.jpg",
        skills: ["xinxhjsaogu"],
        dieAudios: ["duanjiong"],
    },
    xinxhj_yj_ganning: {
        sex: "male",
        group: "qun",
        hp: 4,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/xinxhj_yj_ganning.png",
        skills: ["xinxhjjinfan", "xinxhjsheque"],
        dieAudios: ["yj_ganning"],
    },
    xinxhj_friend_shitao: {
        sex: "male",
        group: "qun",
        hp: 4,
        trashBin: ['rare'],
        tempname: ["friend_shitao"],
        img: "extension/永夜之境/image/xinxhj_friend_shitao.png",
        skills: ["xinxhjqinying", "xinxhjlunxiong", "xinxhj_friendgongli_shitao"],
    },
    xinxhj_dc_caoshuang: {
        sex: "male",
        group: "wei",
        hp: 4,
        trashBin: ['rare'],
        img: "extension/永夜之境/image/xinxhj_dc_caoshuang.png",
        tempname: ["dc_caoshuang"],
        skills: ["xinxhjjianzhuan", "xinxhjfanshi"],
        dieAudios: ["dc_caoshuang"],
    },
    xinxhj_sb_pangtong: {
        sex: "male",
        group: "shu",
        hp: 3,
        trashBin: ['legend'],
        tempname: ["dc_sb_pangtong"],
        img: "image/character/dc_sb_pangtong.jpg",
        skills: ["xinxhjsbyinmou", "xinxhjsbhongce"],
        dieAudios: ["dc_sb_pangtong"],
    },
};

export const character = {
    ...xinx1Character,
    ...xinx2Character,
    ...xinxfengyuCharacter,
    ...xinxhuaijiuCharacter,
};

export default character;