import { lib, game, ui, get, ai, _status } from '../../../noname.js';
export let voices = {

    //流萤
    '#ext:永夜之境/audio/xinxyingshi1': '这不止是一场战役。',
    '#ext:永夜之境/audio/xinxyingshi2': '火萤Ⅳ型，已就位。',
    '#ext:永夜之境/audio/xinxyingshi3': '火萤Ⅳ型，等待指示。',
    '#ext:永夜之境/audio/xinxyingshi4': '行动四，点火。',
    '#ext:永夜之境/audio/xinxyingshi5': '没有退路，只能向前。',
    '#ext:永夜之境/audio/xinxyingshi_xinx_liuying_shadow1': '为战而生，为生而战！',
    '#ext:永夜之境/audio/xinxyingshi_xinx_liuying_shadow2': '我将，点燃星海！',
    '#ext:永夜之境/audio/xinxyingshi_xinx_liuying_shadow3': '我会为自己夺得胜利。',
    '#ext:永夜之境/audio/xinxyingshi_xinx_liuying_shadow4': '行动四，点火。',
    '#ext:永夜之境/audio/xinxyingshi_xinx_liuying_shadow5': '没有退路，只能向前。',
    '#ext:永夜之境/audio/xinxxinzhui1': '飞萤扑火，向死而生。',
    '#ext:永夜之境/audio/xinxxinzhui2': '我为自我而战，直至一切…燃烧殆尽！',
    '#ext:永夜之境/audio/xinxxinzhui3': '也许最后，我也能拥有自己的梦……',
    '#ext:永夜之境/audio/xinxxinzhui4': '薄如蝉翼的生命，也有璀璨燃烧的可能。',
    '#ext:永夜之境/audio/xinxxinzhui5': '切换预案。',
    '#ext:永夜之境/audio/xinxxinzhui6': '受到攻击。',
    "#ext:永夜之境/audio/die/xinx_liuying:die": "任务…终止……",
    "#ext:永夜之境/audio/die/xinx_liuying_shadow:die": "任务…终止……",

    //镜流
    '#ext:永夜之境/audio/xinxxiaguang1': '现在退下，我便饶你一命。',
    '#ext:永夜之境/audio/xinxxiaguang2': '无趣。',
    '#ext:永夜之境/audio/xinxxiaguang3': '飞光流泻！',
    '#ext:永夜之境/audio/xinxxiaguang4': '剑出无回！',
    '#ext:永夜之境/audio/xinxxiaguang5': '多添一条亡魂罢了。',
    '#ext:永夜之境/audio/xinxxiaguang6': '不值一哂。',
    '#ext:永夜之境/audio/xinxshuohua1': '我以月色为剑。',
    '#ext:永夜之境/audio/xinxshuohua2': '剑下草芥！',
    '#ext:永夜之境/audio/xinxshuohua3': '就让这一轮月华…照彻万川！',
    '#ext:永夜之境/audio/xinxshuohua4': '准备受死…',
    '#ext:永夜之境/audio/xinxshuohua5': '你无处可逃！',

    //刃
    '#ext:永夜之境/audio/xinxzhili1': '其势…已成！',
    '#ext:永夜之境/audio/xinxzhili2': '死兆…将至！',
    '#ext:永夜之境/audio/xinxzhili3': '以掌中之剑，送你一程。',
    '#ext:永夜之境/audio/xinxzhili4': '剑下不必留情。',
    '#ext:永夜之境/audio/xinxzhili5': '生命，已成惩戒。',
    '#ext:永夜之境/audio/xinxzhili6': '已死之人，不知所惧。',
    '#ext:永夜之境/audio/xinxfandu1': '彼岸…葬送！',
    '#ext:永夜之境/audio/xinxfandu2': '此番美景，我虽求而不得……',
    '#ext:永夜之境/audio/xinxfandu3': '却能，邀诸位共赏。',
    '#ext:永夜之境/audio/xinxfandu4': '还不够……',
    '#ext:永夜之境/audio/xinxfandu5': '好，来得好。',

    //黄泉
    '#ext:永夜之境/audio/xinxleizhi1': '流淌吧…过往的刀光。',
    '#ext:永夜之境/audio/xinxleizhi2': '暴雨将至。',
    '#ext:永夜之境/audio/xinxleizhi3': '你要去哪？',
    '#ext:永夜之境/audio/xinxleizhi4': '无妨，就在此了结。',
    '#ext:永夜之境/audio/xinxleizhi5': '也好，舍去了挣扎的工夫。',
    '#ext:永夜之境/audio/xinxcanmeng1': '此生如朝露，身名俱灭。',
    '#ext:永夜之境/audio/xinxcanmeng2': '忘川无波澜，引渡徘徊。',
    '#ext:永夜之境/audio/xinxjizhen1': '我为逝者哀哭……',
    '#ext:永夜之境/audio/xinxliaoduan1': '暮雨，终将落下。',
    '#ext:永夜之境/audio/xinxliaoduan2': '又一场雨，一场空白。',

    //白厄
    '#ext:永夜之境/audio/xinxzhuhuo1': '点燃黎明！',
    '#ext:永夜之境/audio/xinxzhuhuo2': '此身的火焰，还不够猛烈。',
    '#ext:永夜之境/audio/xinxzhuhuo3': '新世界，终将到来！',
    '#ext:永夜之境/audio/xinxzhuhuo4': '为了，下一个明天！',
    '#ext:永夜之境/audio/xinxzhuhuo5': '除了向前，别无选择。',
    '#ext:永夜之境/audio/xinxzhuhuo_xinx_baie_shadow1': '铭记这道痛楚！',
    '#ext:永夜之境/audio/xinxzhuhuo_xinx_baie_shadow2': '体会到了么？被仇恨灼烧的滋味。',
    '#ext:永夜之境/audio/xinxzhuhuo_xinx_baie_shadow3': '烙印纷争之名！',
    '#ext:永夜之境/audio/xinxzhuhuo_xinx_baie_shadow4': '熔毁长夜吧！',
    '#ext:永夜之境/audio/xinxzhuhuo_xinx_baie_shadow5': '挣脱囚笼吧！',
    '#ext:永夜之境/audio/xinxfushi1': '我绝不顺从此种命运。',
    '#ext:永夜之境/audio/xinxfushi2': '无妨。我会再次押上一切。',
    '#ext:永夜之境/audio/xinxfushi3': '亿万火种之怒，燃尽此身！',
    '#ext:永夜之境/audio/xinxyongjie1': '以血，淬火！',
    '#ext:永夜之境/audio/xinxyongjie2': '别让时间白白燃烧。',
    '#ext:永夜之境/audio/xinxyongjie3': '以旧日余烬，为来世破晓！',
    '#ext:永夜之境/audio/xinxyongjie4': '以新生的烈阳，撕裂长空！',
    '#ext:永夜之境/audio/xinxyongjie5': '赐你，众星俱焚的曙光。',


    //遐蝶
    '#ext:永夜之境/audio/xinxxsusheng1': '破茧而生。',
    '#ext:永夜之境/audio/xinxxsusheng2': '拥抱新生吧，玻吕刻斯。',
    '#ext:永夜之境/audio/xinxxsusheng3': '请珍惜灵魂还未枯萎的时光。',
    '#ext:永夜之境/audio/xinxxsusheng4': '生命并非如蝶翼般易折。',
    '#ext:永夜之境/audio/xinxxmingxi1': '惟愿死亡……捍卫你我！',
    '#ext:永夜之境/audio/xinxxmingxi2': '太好了……还未到告别之时。',
    '#ext:永夜之境/audio/xinxxmingxi3': '我会铭记此刻的温度。',
    '#ext:永夜之境/audio/xinxxmingxi4': '暗幕，随我同行。',
    '#ext:永夜之境/audio/xinxxmingxi5': '亡魂，返归尘土。',
    '#ext:永夜之境/audio/xinxhuiyi1': '请就此凋零。',
    '#ext:永夜之境/audio/xinxhuiyi2': '赐予你所求。',


    //穹
    '#ext:永夜之境/audio/xinxkaituo1': '休整完毕。',
    '#ext:永夜之境/audio/xinxkaituo2': '敬请期待。',
    '#ext:永夜之境/audio/xinxkaituo3': '存护之志。',
    '#ext:永夜之境/audio/xinxhuanling1': '来吧，就决定是你了！',
    '#ext:永夜之境/audio/xinxhuanling2': '我们，什么都做得到。',
    '#ext:永夜之境/audio/xinxhuanling3': '不慌，还有我在。',
    '#ext:永夜之境/audio/xinxhuanling4': '放心，你可以的。',
    '#ext:永夜之境/audio/xinxcilian1': '这就是心有灵犀的感觉？',
    '#ext:永夜之境/audio/xinxcilian2': '没关系，我会出手。',
    '#ext:永夜之境/audio/xinxcilian3': '这个点子不错。',
    '#ext:永夜之境/audio/xinxcilian4': '相信我吧。',
    '#ext:永夜之境/audio/xinxjizou1': '气氛已经烘托到位。',
    '#ext:永夜之境/audio/xinxjizou2': '到我了。',
    '#ext:永夜之境/audio/xinxjizou3': '合演，开场！',
    '#ext:永夜之境/audio/xinxjizou4': '即兴表演！',
    '#ext:永夜之境/audio/xinxjizou5': '绝佳配合。',
    '#ext:永夜之境/audio/xinxjizou6': '保持步调一致。',
    '#ext:永夜之境/audio/xinxmengxing1': '好梦成真！',
    '#ext:永夜之境/audio/xinxmengxing2': '小心错过入场的最佳时机。',
    '#ext:永夜之境/audio/xinxzhupo1': '以强援弱！',
    '#ext:永夜之境/audio/xinxzhupo2': '坚不可摧！',
    '#ext:永夜之境/audio/xinxzhupo3': '毫发无伤。',
    '#ext:永夜之境/audio/xinxzhupo4': '我绝不后退。',
    '#ext:永夜之境/audio/xinxyanqiang1': '枪尖已经点燃……',
    '#ext:永夜之境/audio/xinxyanqiang2': '炎枪，冲锋！',
    '#ext:永夜之境/audio/xinxyanqiang3': '裂地！',
    '#ext:永夜之境/audio/xinxyanqiang4': '贯穿！',
    '#ext:永夜之境/audio/xinxhuoban1': '我们联手，就是无所不能的！',
    '#ext:永夜之境/audio/xinxhuoban2': '做得好哇，迷迷！',
    '#ext:永夜之境/audio/xinxhuoban3': '想打倒我？没那么容易。',
    '#ext:永夜之境/audio/xinxhuoban4': '再这样试试呢…',

    //星
    '#ext:永夜之境/audio/xinxzhanshu1': '再这样试试呢…',
    '#ext:永夜之境/audio/xinxzhanshu2': '记着点。',
    '#ext:永夜之境/audio/xinxzhanshu3': '节奏乱了？',
    '#ext:永夜之境/audio/xinxdashi1': '到我了。',
    '#ext:永夜之境/audio/xinxdashi2': '没关系，我会出手。',
    '#ext:永夜之境/audio/xinxdashi3': '相信我吧。',
    '#ext:永夜之境/audio/xinxdashi4': '休整完毕。',
    '#ext:永夜之境/audio/xinxdashi5': '嗯…反正我不急。',
    '#ext:永夜之境/audio/xinxdashi6': '气氛已经烘托到位。',
    '#ext:永夜之境/audio/xinxdashi7': '保持步调一致。',
    '#ext:永夜之境/audio/xinxdashi8': '绝佳配合。',

    //长夜月
    '#ext:永夜之境/audio/xinxyiyu1': '听话，该登场了~',
    '#ext:永夜之境/audio/xinxyiyu2': '好好招待大家~',
    '#ext:永夜之境/audio/xinxyiyu3': '诸位，后会有期~',
    '#ext:永夜之境/audio/xinxyiyu4': '天亮了，该醒啦~',
    '#ext:永夜之境/audio/xinxbuli1': '等会就让你们安静下来~',
    '#ext:永夜之境/audio/xinxbuli2': '好啦，不要再胡闹啦。',
    '#ext:永夜之境/audio/xinxbuli3': '记忆的种子，将在雨中萌发。',
    '#ext:永夜之境/audio/xinxbuli4': '夜色将要落幕…',
    '#ext:永夜之境/audio/xinxbuli5': '嘘，晚安。',
    '#ext:永夜之境/audio/xinxbuli6': '命运般的邂逅，不是么？',
    '#ext:永夜之境/audio/xinxbuli7': '也算一段不错的回忆。',

    //华流萤
    '#ext:永夜之境/audio/xinxyueding1': '一步一步，总会实现梦想的，对吧。',
    '#ext:永夜之境/audio/xinxyueding2': '不用紧张，就像之前那样配合吧',

    //昔涟
    '#ext:永夜之境/audio/xinxyilian1': '收下吧，我们的答案～',
    '#ext:永夜之境/audio/xinxyilian2': '翻开吧，永恒的一页。',
    '#ext:永夜之境/audio/xinxyilian3': '准备好唤醒涟漪了吗？',
    '#ext:永夜之境/audio/xinxyilian4': '让刹那，成为永恒～',
    '#ext:永夜之境/audio/xinxyilian5': '以我为因，改写毁灭。',
    '#ext:永夜之境/audio/xinxyilian6': '以爱为因，涤荡憎恨。',
    '#ext:永夜之境/audio/xinxyilian7': '开始第二乐章吧。',
    '#ext:永夜之境/audio/xinxyilian8': '嘻，到人家表现啦♪',
    '#ext:永夜之境/audio/xinxyilian9': '无论过去多久，我都会等你♪',
    '#ext:永夜之境/audio/xinxyilian10': '与你一起，我们无所不能。',
    '#ext:永夜之境/audio/xinxyilian11': '放心。只要我们在一起，什么都能做到。',
    '#ext:永夜之境/audio/xinxyilian12': '别担心，我们还有好多好多时间。',
    '#ext:永夜之境/audio/xinxyilian13': '以爱为始的故事，也一定以爱为终♪',
    '#ext:永夜之境/audio/xinxyilian14': '一步、一步，踩下我们的脚印吧？',
    '#ext:永夜之境/audio/xinxyilian15': '下一页是空白呢，那我们一起写下吧？',
    '#ext:永夜之境/audio/xinxyilian16': '别眨眼哦，有惊喜～',
    '#ext:永夜之境/audio/xinxyilian17': '又是一道优美的诗行。',

    //希儿
    '#ext:永夜之境/audio/xinxguiren1': '随蝴蝶一起消散吧…',
    '#ext:永夜之境/audio/xinxguiren2': '旧日的幻影。',
    '#ext:永夜之境/audio/xinxzaixian1': '这就让你解脱。',
    '#ext:永夜之境/audio/xinxzaixian2': '早点给你个痛快。',
    '#ext:永夜之境/audio/xinxzaixian3': '下一个。',
    '#ext:永夜之境/audio/xinxzaixian4': '原来你怕我。',
    '#ext:永夜之境/audio/xinxzaixian5': '快点，让我试试这招。',
    '#ext:永夜之境/audio/xinxzaixian6': '有目标，镰刀才够快。',

    //布洛妮娅
    '#ext:永夜之境/audio/xinxxianji1': '时不再至，请助我一臂之力！',
    '#ext:永夜之境/audio/xinxxianji2': '时不再至，请随我一同出战！',
    '#ext:永夜之境/audio/xinxxianji3': '你会为此付出代价。',
    '#ext:永夜之境/audio/xinxxianji4': '必须抓住这次机会。',
    '#ext:永夜之境/audio/xinxxianji5': '将我们所失去的，全部夺回。',
    '#ext:永夜之境/audio/xinxxianji6': '别放过任何一处破绽。',
    '#ext:永夜之境/audio/xinxxianji7': '拿出魄力来。',
    '#ext:永夜之境/audio/xinxxianji8': '强敌当前，及时调整战略。',
    '#ext:永夜之境/audio/xinxkejie1': '我们早已踏入风暴。',
    '#ext:永夜之境/audio/xinxkejie2': '为了守护和捍卫，击溃他们！',

    //丝柯克
    '#ext:永夜之境/audio/xinxzhuiyuan1': '尽没。',
    '#ext:永夜之境/audio/xinxzhuiyuan2': '湮散。',
    '#ext:永夜之境/audio/xinxzhuiyuan3': '溢流。',
    '#ext:永夜之境/audio/xinxzhuiyuan4': '破空。',
    '#ext:永夜之境/audio/xinxzhuiyuan5': '踏刃。',
    '#ext:永夜之境/audio/xinxzhuiyuan6': '更迭万象！',
    '#ext:永夜之境/audio/xinxzhuiyuan7': '群星寂灭！',
    '#ext:永夜之境/audio/xinxzhuiyuan8': '沉于渊海！',
    '#ext:永夜之境/audio/xinxliuduan1': '归于我。',

    //大黑塔
    '#ext:永夜之境/audio/xinxjiegou1': '啊…这？拿去玩吧～',
    '#ext:永夜之境/audio/xinxjiegou2': '别稀罕了，我有更好的。',
    '#ext:永夜之境/audio/xinxjiegou3': '怎么，没见过好看的？',
    '#ext:永夜之境/audio/xinxjiegou4': '我觉得…也就那样吧。',    
    '#ext:永夜之境/audio/xinxjiegou5': '洞见未知的瞬间，为它沉迷吧。',
    '#ext:永夜之境/audio/xinxjiegou6': '筑就空域的壁垒，就此塌落吧。',
    '#ext:永夜之境/audio/xinxlinggan1': '就得打开思路～',
    '#ext:永夜之境/audio/xinxlinggan2': '新世界的大门～',
    '#ext:永夜之境/audio/xinxlinggan3': '看见没，这就是天才。',
    '#ext:永夜之境/audio/xinxlinggan4': '真厉害，不愧是我。',
    '#ext:永夜之境/audio/xinxlinggan5': '谜题千千万万，但谜底却是…乌有之物。',

    //星期日
    '#ext:永夜之境/audio/xinxangang1': '我已听见呼唤。',
    '#ext:永夜之境/audio/xinxangang2': '我将越过荆棘。',
    '#ext:永夜之境/audio/xinxangang3': '绝死而能逢生。',
    '#ext:永夜之境/audio/xinxangang4': '你所求的，便是你所得的。',
    '#ext:永夜之境/audio/xinxxunji1': '以此身躯。',
    '#ext:永夜之境/audio/xinxxunji2': '护你左右。',
    '#ext:永夜之境/audio/xinxxunji3': '领你远行。',
    '#ext:永夜之境/audio/xinxxunji4': '纵使遍地荆棘，也当砥砺前行。',
    '#ext:永夜之境/audio/xinxxunji5': '循此苦旅，得见群星。',
    '#ext:永夜之境/audio/xinxxunji6': '愿你我行于坦途，终抵繁星。',

    //风堇
    '#ext:永夜之境/audio/xinxtianqi1': '也请你打开心房吧。',
    '#ext:永夜之境/audio/xinxtianqi2': '请为我们照亮前路。',
    '#ext:永夜之境/audio/xinxtianqi3': '我会以虹桥为指引。',
    '#ext:永夜之境/audio/xinxtianqi4': '拨开阴翳与云雾，重见澄澈晴空！',
    '#ext:永夜之境/audio/xinxhongzhu1': '大家等我们很久啦。',
    '#ext:永夜之境/audio/xinxhongzhu2': '是得好好晒个太阳。',
    '#ext:永夜之境/audio/xinxhongzhu3': '荧荧微光，也将汇成璀璨星河。',
    '#ext:永夜之境/audio/xinxhongzhu4': '愿我们抵达的终点，再无阴霾。',
    '#ext:永夜之境/audio/xinxhongzhu5': '疗愈世间，还需更灿烂的色彩。',
    '#ext:永夜之境/audio/xinxhongzhu6': '天空一无所有，却能予人以安慰。',
    '#ext:永夜之境/audio/xinxhongzhu7': '前路，已被微光照亮。',

    //叶瞬光
    '#ext:永夜之境/audio/xinxlingxiao1': '破寒川。',
    '#ext:永夜之境/audio/xinxlingxiao2': '流云意。',
    '#ext:永夜之境/audio/xinxlingxiao3': '斩冥光。',
    '#ext:永夜之境/audio/xinxlingxiao4': '剑随我意，风朔九天。',
    '#ext:永夜之境/audio/xinxlingxiao5': '仗剑诛邪，此意凌霄。',
    '#ext:永夜之境/audio/xinxlingxiao6': '三尺青锋，斩尽红尘。',
    '#ext:永夜之境/audio/xinxlingxiao_xinx_yeshunguang_shadow1': '霜雪明。',
    '#ext:永夜之境/audio/xinxlingxiao_xinx_yeshunguang_shadow2': '照云霓。',
    '#ext:永夜之境/audio/xinxlingxiao_xinx_yeshunguang_shadow3': '向天横。',
    '#ext:永夜之境/audio/xinxlingxiao_xinx_yeshunguang_shadow4': '以此剑阵，前来送你一程。',
    '#ext:永夜之境/audio/xinxlingxiao_xinx_yeshunguang_shadow5': '云岿山叶瞬光，以此剑破妄。',
    '#ext:永夜之境/audio/xinxlingxiao_xinx_yeshunguang_shadow6': '青溟浩荡，斩断九霄。',
    '#ext:永夜之境/audio/xinxguichen1': '呀！',
    '#ext:永夜之境/audio/xinxguichen2': '呀！',
    '#ext:永夜之境/audio/xinxguichen3': '特！',
    '#ext:永夜之境/audio/xinxguichen4': '嘿啊！',
    '#ext:永夜之境/audio/xinxguichen5': '嘿！',
    '#ext:永夜之境/audio/xinxguichen6': '喝！',
    '#ext:永夜之境/audio/xinxguichen_xinx_yeshunguang_shadow1': '斥！',
    '#ext:永夜之境/audio/xinxguichen_xinx_yeshunguang_shadow2': '喝！',
    '#ext:永夜之境/audio/xinxguichen_xinx_yeshunguang_shadow3': '架！',
    '#ext:永夜之境/audio/xinxguichen_xinx_yeshunguang_shadow4': '哼。',
    '#ext:永夜之境/audio/xinxguichen_xinx_yeshunguang_shadow5': '呲呵。',
    '#ext:永夜之境/audio/xinxguichen_xinx_yeshunguang_shadow6': '呵。',
    '#ext:永夜之境/audio/xinxmingxin1': '剑随我意。',
    '#ext:永夜之境/audio/xinxmingxin2': '仗剑诛邪。',
    '#ext:永夜之境/audio/xinxmingxin3': '三尺青锋。',
    '#ext:永夜之境/audio/xinxmingxin_xinx_yeshunguang_shadow1': '尺素寒霜。',
    '#ext:永夜之境/audio/xinxmingxin_xinx_yeshunguang_shadow2': '点寒芒。',
    '#ext:永夜之境/audio/xinxmingxin_xinx_yeshunguang_shadow3': '一线天。',




    
   










    //风雨如晦
    '#ext:永夜之境/audio/fyrhzhiwen1': '闻士执三尺剑而节义，妾可执三寸刃而绝命乎？',
    '#ext:永夜之境/audio/fyrhzhiwen2': '愿以温血暖冷锋，愿以此命守贞良。',
    '#ext:永夜之境/audio/fyrhminnian1': '曾与君言誓白首，青丝未雪君先逝。',
    '#ext:永夜之境/audio/fyrhminnian2': '可以明灯妆白头，此去黄泉未违誓。',
    '#ext:永夜之境/audio/fyrhfenjue1': '我以节义待人，然人待我何其薄也。',
    '#ext:永夜之境/audio/xinxsian1': '居南为彼，常言道彼者不拗此者之钢锋。',
    '#ext:永夜之境/audio/xinxsian2': '以守为攻，敌来自为我军所败。',
    '#ext:永夜之境/audio/xinxsian3': '兵势无常，善守者可居不败之地。',
    '#ext:永夜之境/audio/xinxsitui1': '江北霜雪，江左春风，晓一经可通五义。',
    '#ext:永夜之境/audio/xinxsitui2': '督军为营，奉师为教，可使麾下双全文武。',
    '#ext:永夜之境/audio/xinxsizhan1': '以文谋佐武勇，此为大善。',
    '#ext:永夜之境/audio/xinxsizhan2': '奉普为师，以教将吏子弟。',
    '#ext:永夜之境/audio/xinxfenjiao1': '此地已战乱如此，不如再加一把。哈哈哈哈哈。',
    '#ext:永夜之境/audio/xinxfenjiao2': '乱战之中，吾自有妙计。',
    '#ext:永夜之境/audio/xinxfenjiao3': '敌军已动摇，正好趁乱取利!',
    '#ext:永夜之境/audio/xinxfenjiao4': '挥槌争天下，飞羽乱世间。',
    '#ext:永夜之境/audio/xinxjilang1': '兵强马壮，自当奋励前进!',
    '#ext:永夜之境/audio/xinxjilang2': '勃然奋励，不可恐慑也。',
    '#ext:永夜之境/audio/xinxjilang3': '势气正锐，可缴穷寇!',
    '#ext:永夜之境/audio/xinxjilang4': '一鼓作气，平寇杀敌!',
    '#ext:永夜之境/audio/xinxyuwei1': '刃如霜，寒胜雪，轻吻神兵，此日战沙场！',
    '#ext:永夜之境/audio/xinxyuwei2': '月华洗锋刃，素手握长缨，红袖欲缚苍龙！',
    '#ext:永夜之境/audio/xinxbailian1': '先人有夺人之心，此平贼之要。',
    '#ext:永夜之境/audio/xinxbailian2': '奇正变通，虚实惑敌。',
    '#ext:永夜之境/audio/xinxbailian3': '先为不可胜，以待敌之可胜。',
    '#ext:永夜之境/audio/xinxbailian4': '以蚕食之计，吞顽抗之敌。',
    '#ext:永夜之境/audio/xinxcongzu1': '用兵当以奇为先。',
    '#ext:永夜之境/audio/xinxcongzu2': '奇兵百出，敌军自溃。',
    '#ext:永夜之境/audio/xinxyibian1': '将贵专谋，兵以奇胜。',
    '#ext:永夜之境/audio/xinxyibian2': '兵善用奇，乃以决胜。',
    





  


    


  





    //杏雅三国
    '#ext:永夜之境/audio/xinxchenlan1': '宦海沉浮，历尽风浪，方显英雄本色。',
    '#ext:永夜之境/audio/xinxchenlan2': '壁立千仞，泰然本英雄！',
    '#ext:永夜之境/audio/xinxchenlan3': '不动如山，气定神闲。',
    '#ext:永夜之境/audio/xinxchenlan4': '胸怀若谷，波澜不惊。',
    '#ext:永夜之境/audio/xinxyiyue1': '不要小瞧了女人。',
    '#ext:永夜之境/audio/xinxyiyue2': '你愿意，为了我而死吗？',
    '#ext:永夜之境/audio/xinxcangren1': '大逆无道，罪当伏诛！',
    '#ext:永夜之境/audio/xinxcangren2': '族消仇逆，以血遗恨！',
    '#ext:永夜之境/audio/xinxcangren3': '此贼不除，我心中仇恨难消！',
    '#ext:永夜之境/audio/xinxcangren4': '这把匕首，可是为你专门准备的。',
    '#ext:永夜之境/audio/xinxcangren5': '汝等奸贼，何当今日丧命！',
    '#ext:永夜之境/audio/xinxcangren6': '含恨谋划，忍辱数年，只为今日！',
    '#ext:永夜之境/audio/xinxfenglu1': '这把匕首，就是为你准备的！',
    '#ext:永夜之境/audio/xinxfenglu2': '诛杀逆贼，我决不手软！',
    '#ext:永夜之境/audio/xinxtianzhi1': '嘉不受此劫，安能以凡人之躯窥得天机！',
    '#ext:永夜之境/audio/xinxtianzhi2': '绸缪于未雨，手握胜机，雨落何妨高歌？',
    '#ext:永夜之境/audio/xinxshisheng1': '公有此十胜，败绍非难事尔。',
    '#ext:永夜之境/audio/xinxshisheng2': '嘉窃料之，绍有十败，公有十胜。',
    '#ext:永夜之境/audio/xinxquanmou1': '且施小策，以襄伯约之谋。',
    '#ext:永夜之境/audio/xinxquanmou2': '伯约疲敌之法，吾亦精擅。',
    '#ext:永夜之境/audio/xinxquanmou3': '吾得伯约一心，大事必成！',
    '#ext:永夜之境/audio/xinxquanmou4': '以吾与伯约之智，必可无虞。',
    '#ext:永夜之境/audio/xinxquanmou5': '莽行轻进，不如缓进徐图。',
    '#ext:永夜之境/audio/xinxquanmou6': '谋谟帷幄之间，定断未来之局。',
    '#ext:永夜之境/audio/xinxwuyi1': '汝居功自傲，致有吾施谋之机。',
    '#ext:永夜之境/audio/xinxwuyi2': '天下唾手可得，岂容宵小妄为？',
    '#ext:永夜之境/audio/xinxwuyi3': '借君之手，扫除所惮之敌。',
    '#ext:永夜之境/audio/xinxwuyi4': '虚己诱纳，自可得吾所欲。',
    '#ext:永夜之境/audio/xinxhuoji1': '恩仇付浊酒，荡平劫波，且做英雄吼。',
    '#ext:永夜之境/audio/xinxhuoji2': '不周之柱已折，这世间，当起一阵风，落一场雨！',
    '#ext:永夜之境/audio/xinxhuoji3': '谋先于行则昌，行先于谋则亡。',
    '#ext:永夜之境/audio/xinxhuoji4': '善谋者，不与善战者争功。',
    '#ext:永夜之境/audio/xinxcanjing1': '曾寄青鸟凌云志，归来城头看王旗。',
    '#ext:永夜之境/audio/xinxcanjing2': '烽火照长安，清水洗枯骨，今日对弈何人？',
    '#ext:永夜之境/audio/xinxjuewu1': '下一次，轮到谁了？',
    '#ext:永夜之境/audio/xinxjuewu2': '上吧，就像扑火的飞蛾那样。',
    '#ext:永夜之境/audio/xinxqingchen1': '妾之美貌，永不凋零。',
    '#ext:永夜之境/audio/xinxqingchen2': '春伴蝶眷落红满，居何处，妾顾盼。',
    '#ext:永夜之境/audio/xinxqingchen3': '你们会喜欢的。',
    '#ext:永夜之境/audio/xinxqingchen4': '又美了几分呢。',
    '#ext:永夜之境/audio/xinxqingchen5': '嗯呵呵，美貌的胜利。',
    '#ext:永夜之境/audio/xinxqingchen6': '我美吗？',
    '#ext:永夜之境/audio/xinxxieling1': '严刑正法，奸鬼不敢前！',
    '#ext:永夜之境/audio/xinxxieling2': '犯吾禁令者，虽豪强权贵，亦当严惩！',
    '#ext:永夜之境/audio/xinxxieling3': '妇人之仁，焉能成大事？',
    '#ext:永夜之境/audio/xinxxieling4': '挟天子以令不臣！',
    '#ext:永夜之境/audio/xinxjianxiong1': '既定九州乱，雄吞天下兵！',
    '#ext:永夜之境/audio/xinxjianxiong2': '为谋天下一统，何惜眼前小损！',
    '#ext:永夜之境/audio/xinxjianxiong3': '恨其才不为我所用，宁杀之亦胜入他人之手。',
    '#ext:永夜之境/audio/xinxjianxiong4': '兵行错役之制，可绝负我之人！',
    '#ext:永夜之境/audio/dz_K_wuqian1': '动作，就是要这样快！',
    '#ext:永夜之境/audio/dz_K_wuqian2': '策马袭敌，乘胜追击！',
    '#ext:永夜之境/audio/dz_K_huanren1': '没有防备我吧？',
    '#ext:永夜之境/audio/dz_K_huanren2': '逍遥津下溃吴侯！',
    '#ext:永夜之境/audio/xinxwugui1': '哼，司马氏可为，吾如何不可为？',
    '#ext:永夜之境/audio/xinxwugui2': '这天下，未必不能姓钟！',
    '#ext:永夜之境/audio/xinxsanku1': '天行五色，雪覆林间睡狐，独我执白。',
    '#ext:永夜之境/audio/xinxsanku2': '已积千里跬步，欲履万里河山。',
    '#ext:永夜之境/audio/xinxsanku3': '我有三窟之筹谋，不蹈背水之维谷。',
    '#ext:永夜之境/audio/xinxsanku4': '九州如画，怎可空老人间？',
    '#ext:永夜之境/audio/xinxluexin1': '飞叶摘星辰，红枫飘落，好似蝴蝶舞。',
    '#ext:永夜之境/audio/xinxluexin2': '月霜凝露华，玉盘白练，遗珠赠明月。',
    '#ext:永夜之境/audio/xinxluexin3': '寒光映霜雪，邀君献命，赠汝雪上一点红！',
    '#ext:永夜之境/audio/xinxluexin4': '以箭做陷，欺张郃于此，诱夏侯分兵。',
    '#ext:永夜之境/audio/xinxyangjian1': '箭射天外，可毙天狼！',
    '#ext:永夜之境/audio/xinxyangjian2': '举弓望北，箭狩群星。',
    '#ext:永夜之境/audio/xinxyangjian3': '长弓在手，可效龙城飞将，箭没在野石棱！',
    '#ext:永夜之境/audio/xinxyangjian4': '金矢鸣锋镝，飞羽漫云，鞭长可击九霄！',
    '#ext:永夜之境/audio/xinxjinbi1': '士大夫之流，不过尔尔。',
    '#ext:永夜之境/audio/xinxjinbi2': '哼，毛贼而已。',
    '#ext:永夜之境/audio/xinxjinbi3': '汉水暴溢，是进攻之机！',
    '#ext:永夜之境/audio/xinxjinbi4': '樊城之乱，是某之良机。',
    '#ext:永夜之境/audio/xinxqizhen1': '兵之用者，其状不定见也。',
    '#ext:永夜之境/audio/xinxqizhen2': '因势而动，变生于阵之间。',
    '#ext:永夜之境/audio/xinxqizhen3': '天覆地载，龙变其中。',
    '#ext:永夜之境/audio/xinxqizhen4': '行则为阵，立则为营。',
    '#ext:永夜之境/audio/xinxshiyu1': '区区雕虫小技，微不足道矣。',
    '#ext:永夜之境/audio/xinxshiyu2': '识众寡之用者，胜之。',
    '#ext:永夜之境/audio/xinxshiyu3': '此……小儿之计乎？哈哈哈哈！',
    '#ext:永夜之境/audio/xinxshiyu4': '汝予智予雄，殊不知，吾早已看破。',
    '#ext:永夜之境/audio/xinxlihuo1': '以火焚敌，乱其行阵。',
    '#ext:永夜之境/audio/xinxlihuo2': '赤焰飚发，焚轻舟，坠敌身。',
    '#ext:永夜之境/audio/xinxlihuo3': '诱敌深入，焚其粮草，敌无委积，必败！',
    '#ext:永夜之境/audio/xinxlihuo4': '天时地利，更兼人和，佐以火攻，必胜！',
    '#ext:永夜之境/audio/xinxzhaohan1': '此身抱薪，可付丹鼎，五十四年春秋昭炎汉长明。',
    '#ext:永夜之境/audio/xinxzhaohan2': '南征北伐，誓还旧都，二十四代王业不偏安一隅。',
    '#ext:永夜之境/audio/xinxzhaohan3': '情寄三顾之恩，亮必继之以死。',
    '#ext:永夜之境/audio/xinxzhaohan4': '身负六尺之孤，臣当鞠躬尽瘁。',
    '#ext:永夜之境/audio/xinxrenshi1': '兵者，行霸道之势，彰王道之实。',
    '#ext:永夜之境/audio/xinxrenshi2': '将为军魂，可因势而袭，其有战无类。',
    '#ext:永夜之境/audio/xinxrenshi3': '平二川，定三足，恍惚草堂梦里，挥斥千古风流。',
    '#ext:永夜之境/audio/xinxrenshi4': '战群儒，守空城，今摆乱石八阵，笑谈将军死生。',
    '#ext:永夜之境/audio/xinxchushi1': '轻舟载浊酒，此去，我欲借箭十万。',
    '#ext:永夜之境/audio/xinxchushi2': '主公有多大胆略，亮便有多少谋略。',
    '#ext:永夜之境/audio/xinxxzhaohan1': '此身抱薪，可付丹鼎，五十四年春秋昭炎汉长明。',
    '#ext:永夜之境/audio/xinxxzhaohan2': '南征北伐，誓还旧都，二十四代王业不偏安一隅。',
    '#ext:永夜之境/audio/xinxxzhaohan3': '情寄三顾之恩，亮必继之以死。',
    '#ext:永夜之境/audio/xinxxzhaohan4': '身负六尺之孤，臣当鞠躬尽瘁。',
    '#ext:永夜之境/audio/dz_xing_yinxi1': '知我者谓我心忧，所忧者君尔。',
    '#ext:永夜之境/audio/dz_xing_yinxi2': '我本局中子，上接青云，下怀江河。',
    '#ext:永夜之境/audio/dz_xing_yinxi3': '妾御春风细雨，可保君无虞。',
    '#ext:永夜之境/audio/dz_xing_yinxi4': '纵天地将合，悦君之心不移。',
    '#ext:永夜之境/audio/dz_xing_jiangchun1': '求死易，求生难，欲生则畏死。',
    '#ext:永夜之境/audio/dz_xing_jiangchun2': '浊世汹汹，既得白首之人，怎可超然物外。',
    '#ext:永夜之境/audio/xing_xingyu1': '逝者如斯，亘古长流，唯英烈之魂悬北斗而长存！',
    '#ext:永夜之境/audio/xing_xingyu2': '赵氏之女，跪祈诸公勿渡黄泉，暂留人间，佑大汉万年！',
    '#ext:永夜之境/audio/xing_ningshuang1': '当年明月凝霜刃，此日送尔渡黄泉！',
    '#ext:永夜之境/audio/xing_ningshuang2': '已识万里乾坤大，何虑千山草木青！',
    '#ext:永夜之境/audio/xing_zhupo1': '凝傲雪之梅为魄，英魂长存，独耀山河万古明！',
    '#ext:永夜之境/audio/xing_zhupo2': '铸凌霜之寒成剑，青锋出鞘，斩尽天下不臣贼！',
    '#ext:永夜之境/audio/xing_hanming1': '龙凤在侧，五虎在前，天命在汉，既寿永昌！',
    '#ext:永夜之境/audio/xing_hanming2': '人言为信，日月为明，言日月为证，佑大汉长明！',
    '#ext:永夜之境/audio/xxxhuanren1': '由此突破！',
    '#ext:永夜之境/audio/xxxhuanren2': '下役，当活捉孙仲谋。',
    '#ext:永夜之境/audio/xxxzhenxi1': '找到你了！',
    '#ext:永夜之境/audio/xxxzhenxi2': '以霹雳之势，扫平江东！',
    '#ext:永夜之境/audio/xxxzhenxi3': '你躲不掉的。',
    '#ext:永夜之境/audio/xxxzhenxi4': '我会让你哭不出来。',
    '#ext:永夜之境/audio/xinxsongqu1': '洛灵感焉，徙倚彷徨。',
    '#ext:永夜之境/audio/xinxsongqu2': '浮长川而忘返，思绵绵而增慕。',
    '#ext:永夜之境/audio/xinxsongqu3': '忽焉纵体，以遨以嬉。',
    '#ext:永夜之境/audio/xinxsongqu4': '瑰姿艳逸，仪静体闲。',
    '#ext:永夜之境/audio/xinxfushen1': '有美一人，婉如清扬。',
    '#ext:永夜之境/audio/xinxfushen2': '巧笑倩兮，美目盼兮。',
    '#ext:永夜之境/audio/xinxguizi1': '靓糚刻饰，便嬛绰约。',
    '#ext:永夜之境/audio/xinxguizi2': '绝殊离俗，妖冶嫺都。',
    '#ext:永夜之境/audio/xinxchiyu1': '能进能退，方显英雄本色！',
    '#ext:永夜之境/audio/xinxchiyu2': '曹阿瞒的青釭剑，很好用。',
    '#ext:永夜之境/audio/xinxchiyu3': '该胆寒的是他们。',
    '#ext:永夜之境/audio/xinxchiyu4': '云为汉室，无所畏惧！',
    '#ext:永夜之境/audio/xinxshuangmang1': '常山赵子龙，在此！',
    '#ext:永夜之境/audio/xinxshuangmang2': '长枪之下，不留宵小！',
    '#ext:永夜之境/audio/xinxshiren1': '识人读心，评荐推达。',
    '#ext:永夜之境/audio/xinxshiren2': '月旦雅评，试论天下。',
    '#ext:永夜之境/audio/xinxshiren3': '议于草野间，评荐俊才多。',
    '#ext:永夜之境/audio/xinxshiren4': '君清平之奸贼，乱世之英雄。',
    '#ext:永夜之境/audio/xinxshiren5': '千帆过尽，评枭雄之谋，论天下分合！',
    '#ext:永夜之境/audio/xinxshiren6': '三尺毛峰，引九天之水，濯一世功名！',
    '#ext:永夜之境/audio/xinxqianqiu1': '我乘轻舟访人间，人如江鲫逐功名。',
    '#ext:永夜之境/audio/xinxqianqiu2': '一言难道千秋业，一纸雅评半世人。',
    '#ext:永夜之境/audio/xinxzhuoshao1': '这把火，便是我送给尔等的礼物。',
    '#ext:永夜之境/audio/xinxzhuoshao2': '火凭风势！',
    '#ext:永夜之境/audio/xinxcangyan1': '不消一曲，汝必败。',
    '#ext:永夜之境/audio/xinxcangyan2': '妙哉，妙哉。',
    '#ext:永夜之境/audio/xinxcangyan3': '一曲尽兴，余心快哉。',
    '#ext:永夜之境/audio/xinxcangyan4': '请诸君，听我一曲。',
    '#ext:永夜之境/audio/xinxcangyan5': '攻心不定，请回。',
    '#ext:永夜之境/audio/xinxcangyan6': '听琴时，不必说话。',
    '#ext:永夜之境/audio/xing_sizhu1': '此心相印，非山河可阻，兵戈可断。',
    '#ext:永夜之境/audio/xing_sizhu2': '角中有白纹，灵如线，君心我心系两端。',
    '#ext:永夜之境/audio/xing_sizhu_xinx_caoxian_shadow1': '灵犀越千山，君在彼，欲寄青鸟相思十万。',
    '#ext:永夜之境/audio/xing_sizhu_xinx_caoxian_shadow2': '日暮苍山远，雪女怨寒，此心可栖君畔。',
    '#ext:永夜之境/audio/xing_mengran1': '君知春风带暖意，可知丝丝皆妾语？',
    '#ext:永夜之境/audio/xing_mengran2': '愿将满腹相思语，化为春风拂君面。',
    '#ext:永夜之境/audio/xing_mengran_xinx_caoxian_shadow1': '恨名曹，幸为妾，心怀焦炭难两全。',
    '#ext:永夜之境/audio/xing_mengran_xinx_caoxian_shadow2': '君知否，君知否，墙外浓雪杀翠柳。',
    '#ext:永夜之境/audio/xinxpanzhi1': '愿以此身为烛，齐七星之数。',
    '#ext:永夜之境/audio/xinxpanzhi2': '逐阳而战，血染天幕之彤云！',
    '#ext:永夜之境/audio/xinxlinyou1': '我辈慕光而行，不为浮云障目。',
    '#ext:永夜之境/audio/xinxlinyou2': '怀麒麟之志，负柱国之托，奔天涯海角！',
    '#ext:永夜之境/audio/xinxlinyou3': '师恩如山，维所报者，唯此身尔。',
    '#ext:永夜之境/audio/xinxlinyou4': '天下齐喑，我辈秉身为烛，当照四海九州！',
    '#ext:永夜之境/audio/xinxlinyou5': '效逐日之夸父，怀忠志而长存。',
    '#ext:永夜之境/audio/xinxlinyou6': '知天命而不顺，履穷途而强为。',
    '#ext:永夜之境/audio/xinxlinyou7': '炎阳将坠，可为者，唯舍生擎天！',
    '#ext:永夜之境/audio/xinxlinyou8': '维既抱逐日之远志，不在念当归之遐思。',
    '#ext:永夜之境/audio/xinxlinyou9': '孤鸿鸣于野，其以身为奉，引春风入汉关。',
    '#ext:永夜之境/audio/xinxlinyou10': '炎阳在悬，岂因乌云障日而弃金光于野。',
    '#ext:永夜之境/audio/xinxlinyou11': '家国存亡之际，不可弃一线生机。',
    '#ext:永夜之境/audio/xinxlinyou12': '棘路万里，雄关亘原，今乃迈步之始。',
    '#ext:永夜之境/audio/xinxfuhan1': '此生未止，志随先烈之遗风！',
    '#ext:永夜之境/audio/xinxfuhan2': '九州齐喑，我辈燃己长明，君欲同否？',
    '#ext:永夜之境/audio/xinxyice1': '汝等若心存隐忍，顷刻便尸骨无存！',
    '#ext:永夜之境/audio/xinxyice2': '在下所谋之法，唯恐天下不乱！',
    '#ext:永夜之境/audio/xinxwansha1': '吾之所好，杀人诛心。',
    '#ext:永夜之境/audio/xinxwansha2': '汝可遣使相问，四下可有援军？',
    '#ext:永夜之境/audio/xinxshixi1': '将军一副好骨，不如留于此山！',
    '#ext:永夜之境/audio/xinxshixi2': '气势凌人，以智制敌。',
    '#ext:永夜之境/audio/xinxyingfu1': '隐伏暗藏，待敌入阵。',
    '#ext:永夜之境/audio/xinxyingfu2': '设伏布兵，擒贼易如反掌。',
    '#ext:永夜之境/audio/xinxyingfu3': '埋伏在此，就等将军你来了。',
    '#ext:永夜之境/audio/xinxyingfu4': '神藏鬼伏，将军岂能察觉？',
    '#ext:永夜之境/audio/xinxyingfu5': '栖身隐伏，暗查敌情。',
    '#ext:永夜之境/audio/xinxyingfu6': '兼善皆驭，方能稳固。',
    '#ext:永夜之境/audio/xinxqianlong1': '成大事者，当务实权而远虚名。',
    '#ext:永夜之境/audio/xinxqianlong2': '潜龙隐于千丈海，胸有韬晦十万兵。',
    '#ext:永夜之境/audio/xinxqianlong3': '大隐于朝，韬略八方。',
    '#ext:永夜之境/audio/xinxqianlong4': '隐居幕后，挥斥八方。',
    '#ext:永夜之境/audio/xinxyini1': '夷此僚三族，以儆效尤！',
    '#ext:永夜之境/audio/xinxyini2': '逆我司马氏者，罪无可恕！',
    '#ext:永夜之境/audio/xinxqiansi1': '若非天下英雄，吾不事之！',
    '#ext:永夜之境/audio/xinxqiansi2': '擂鼓鸣金皆梦呓，烽烟翻覆绕指柔。',
    '#ext:永夜之境/audio/xinxqiansi3': '我江东女子，绝非孱弱娇嗔之辈。',
    '#ext:永夜之境/audio/xinxqiansi4': '弯弓策马呈肝胆，巾帼何必让须眉?',
    '#ext:永夜之境/audio/xinxxiaoling1': '矢石之间，取你性命。',
    '#ext:永夜之境/audio/xinxxiaoling2': '鞘内无白刃，马下无生魂。',
    '#ext:永夜之境/audio/xinxxiaoling3': '腰间白羽箭，东风为张弓。',
    '#ext:永夜之境/audio/xinxxiaoling4': '策马上阵，不输男儿。',
    '#ext:永夜之境/audio/xinxqueyi1': '满朝尽忠天子，何有不臣之人？',
    '#ext:永夜之境/audio/xinxqueyi2': '九辞封赐，足见臣一片忠心。',
    '#ext:永夜之境/audio/xinxqueyi3': '辅国臣之本分，何敢图于禄勋。',
    '#ext:永夜之境/audio/xinxqueyi4': '蜀贼吴寇未灭，臣未可受此殊荣。',
    '#ext:永夜之境/audio/xinxshexin1': '统摄朝野，威加海内，此皆陛下恩德！',
    '#ext:永夜之境/audio/xinxshexin2': '天下未定，吾当辞邑修身，何敢冒僭？',
    '#ext:永夜之境/audio/xinxshexin3': '天子亲征，淮南之乱，不日可平！',
    '#ext:永夜之境/audio/xinxshexin4': '臣请陛下亲讨乱贼，以昭帝威！',
    '#ext:永夜之境/audio/xinxjinmian1': '陛下有罪，吾当治之以对天下！',
    '#ext:永夜之境/audio/xinxjinmian2': '天下名为曹姓，实归吾司马一族！',
    '#ext:永夜之境/audio/xinxjinmian3': '若得灭蜀之功，何不可受禅为帝。',
    '#ext:永夜之境/audio/xinxjinmian4': '已极人臣之贵，当一尝人主之威。',
    '#ext:永夜之境/audio/xinxsukan1': '吾领三军于外，岂容陛下收政于京！',
    '#ext:永夜之境/audio/xinxsukan2': '吾今大权独揽，何可再予他人？',
    '#ext:永夜之境/audio/xinxsukan3': '平叛淮南，吾司马氏当再立不世之功！',
    '#ext:永夜之境/audio/xinxsukan4': '城破之日，定诛此逆贼三族！',
    '#ext:永夜之境/audio/xinxsukan5': '众将平乱所获，皆为陛下所赐！',
    '#ext:永夜之境/audio/xinxsukan6': '汝等仍存异心，可见心存魏阙。',
    '#ext:永夜之境/audio/xinxsukan7': '哼！斩首示众，以儆效尤。',
    '#ext:永夜之境/audio/xinxbingjun1': '呵呵哈哈哈哈哈……一统之世，当由我司马氏开创！',
    '#ext:永夜之境/audio/xinxbingjun2': '执掌朝野，尽吞大魏河山！',
    '#ext:永夜之境/audio/xinxbingjun3': '明日正为吉日，当举禅位之典。',
    '#ext:永夜之境/audio/xinxchenlue1': '砺剑数载，今青锋始现，欲杀人于十步之内！',
    '#ext:永夜之境/audio/xinxchenlue2': '经年之谋将成，吾辈岂能踌躇。',
    '#ext:永夜之境/audio/xinxchenlue3': '目有创，僵卧于榻上，逢骁将袭营，踏碎夜阑。',
    '#ext:永夜之境/audio/xinxchenlue4': '体弱难着铁衣，有杀贼之心而无力，恨也恨也。',
    '#ext:永夜之境/audio/xinxsanshi1': '寒来暑往，春秋相异，我辈慕白，则九月飞雪！',
    '#ext:永夜之境/audio/xinxsanshi2': '红巾系首枫似火，当曳秋风满洛城！',
    '#ext:永夜之境/audio/xinxsanshi3': '众流汇入江海，可引暗潮漫城。',
    '#ext:永夜之境/audio/xinxsanshi5': '平原养毛遂，孟尝侍朱英，士者怀大义也。',
    '#ext:永夜之境/audio/xinxsanshi4': '鸡鸣狗盗之士，胜满堂之朱紫。',
}